launcher/src/components/UI/LangButton.vue
launcher/src/components/UI/LangDialog.vue
launcher/src/components/layers/BaseLogo.vue
launcher/src/components/layers/TheFirst.vue
launcher/src/router/index.js

added new components and changed the route

start frontend proj

---

launcher/src/components/UI/LangDialog.vue
launcher/src/components/UI/SandClock.vue
launcher/src/components/layers/AddDialog.vue
launcher/src/components/layers/BaseButton.vue
launcher/src/components/layers/BaseDialog.vue
launcher/src/components/layers/SetupServer.vue
launcher/src/components/layers/TheFirst.vue

new upedate

---

launcher/jest.config.js

adding coverage report output format, html is accessible in `launcher/coverage/index.html`

ADD:jest coverage reports

---

controls/roles/manage-service/tasks/main.yml

https://github.com/stereum-dev/ethereum-node/runs/5114236792?check_suite_focus=true#step:7:454

Format fix: SSV-Prysm

---

controls/genericPlaybook.yaml
controls/roles/setup/tasks/main.yml
controls/setup.yaml
launcher/src/backend/NodeConnection.int.js
launcher/src/backend/NodeConnection.js

Exec Command in runPlaybook would fail cause of newlines and missing attribute playbook

ADD: generic Playbook

---

launcher/jest.config.js
launcher/src/components/layers/FormSetup.vue
launcher/src/store/ControlService.js

it's not the prettiest but it works. I also had an error saying `preload.js was not loaded` or something like that. I fixed it by manually copying `preload.js` into `launcher/dist_electron`.

ADD: Wiring to BE for FormSetup, fixed FormSetup

---

launcher/src/storageservice.js

Prevent Stereum 2.x from reading/writing Stereum 1.x local settings.

FIX:local settings overlapping stereum1.0

---

launcher/src/backend/NodeConnection.int.js

Test failed on too many tries to connect. The server got stuck and prevented re-runs from being successful

FIX: Server getting stuck on integration test

---

launcher/src/backend/NodeConnection.int.js

Made a sloppy mistake while refactoring.

FIX: NodeConnection.int.js

---

launcher/src/backend/NodeConnection.int.js

Waiting longer now and logging Server

FIX: NodeConnection.int.js 

---

launcher/src/backend/NodeConnection.int.js

A missing `=` character in an if statement caused deletion of the last server in the array instead of the matching one 🙃

FIX: Test was deleting wrong server

---

launcher/src/components/layers/FormSetup.vue
launcher/src/pages/TheFirst.vue
launcher/vue.config.js

Also fixed the missing preload.js error

ADD: remember chosen Language closes #77

---

.github/workflows/test-molecule.yml

This should fix the syntax error, tested it on my forked repo

ADD: community.docker as dependency in test-molecule.yml

---

controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
controls/roles/manage-service/molecule/ssv-teku/verify.yml

FIX: consensus client ssv test verify timing issue

---

controls/roles/manage-service/tasks/main.yml
controls/roles/validator-import-api/molecule/prysm/prepare.yml

https://github.com/stereum-dev/ethereum-node/issues/162

FIX: Prysm import-API

---

launcher/src/backend/OneClickInstall.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.test.js
launcher/src/backend/ethereum-services/LighthouseValidatorService.js
launcher/src/backend/ethereum-services/LighthouseValidatorService.test.js

`ETH1_NODES: http://stereum-dvAHT3VG-ri5u-YH4H-9i19-S1tETz6LT75n:8545,http://stereum-dvAHT3VG-ri5u-YH4H-9i19-S1tETz6LT75n:8545`
works just right

ADD: Lighthouse to OneClickInstaller

---

controls/roles/validator-import-api/molecule/prysm/molecule.yml

https://github.com/stereum-dev/ethereum-node/issues/162

FIX: Import-API SSH connection

---

controls/roles/validator-import-api/molecule/prysm/molecule.yml

Solution from: https://access.redhat.com/solutions/4683221

FIX: ssh connection issues with molecule test

---

.github/workflows/test-integration.yml
launcher/src/backend/NodeConnection.int.js
launcher/src/backend/NodeConnection.js
launcher/src/backend/ethereum-services/GethService.int.js
launcher/src/backend/ethereum-services/GethService.js
launcher/src/backend/ethereum-services/LighthouseValidatorService.js
launcher/src/backend/ethereum-services/LighthouseValidatorService.test.js
launcher/src/backend/ethereum-services/NimbusBeaconService.int.js
launcher/src/backend/ethereum-services/NimbusBeaconService.js

Also did some smaller adjustments for some integration tests and added more checks

ADD: variable branch selection for tests, tests running on ubuntu 20.04 fixes #249

---

controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
controls/roles/manage-service/molecule/ssv-prysm/verify.yml
controls/roles/manage-service/molecule/ssv-teku/verify.yml

with `v0.1.12`, There is a no Information about ssv-keys in Log output

fix: checking ssv log output

---

controls/roles/update-stereum/molecule/default/converge.yml
controls/roles/update-stereum/molecule/default/create.yml
controls/roles/update-stereum/molecule/default/destroy.yml
controls/roles/update-stereum/molecule/default/molecule.yml
controls/roles/update-stereum/molecule/default/playbook.yml
controls/roles/update-stereum/molecule/default/prepare.yml
controls/roles/update-stereum/molecule/default/verify.yml
controls/roles/update-stereum/molecule/override/converge.yml
controls/roles/update-stereum/molecule/override/create.yml
controls/roles/update-stereum/molecule/override/destroy.yml
controls/roles/update-stereum/molecule/override/molecule.yml
controls/roles/update-stereum/molecule/override/playbook.yml
controls/roles/update-stereum/molecule/override/prepare.yml
controls/roles/update-stereum/molecule/override/verify.yml
controls/roles/update-stereum/tasks/main.yml

Simple update produre for Stereum controls on the node itself. Also 2 tests for update to latest and update to a specific version (via git commit hash) included.

ADD: simple stereum update process

---

controls/roles/validator-import-api/molecule/prysm/verify.yml

error fix: https://github.com/stereum-dev/ethereum-node/runs/6401714005?check_suite_focus=true#step:8:1032

fix: prysm import-api verify

---

controls/roles/manage-service/tasks/main.yml

Open for feedback if there is a better way to do this 😅

FIX: variable path for prysm szz files

---

.github/workflows/test-molecule.yml
controls/roles/validator-import-api/molecule/teku/converge.yml
controls/roles/validator-import-api/molecule/teku/create.yml
controls/roles/validator-import-api/molecule/teku/destroy.yml
controls/roles/validator-import-api/molecule/teku/molecule.yml
controls/roles/validator-import-api/molecule/teku/playbook.yml
controls/roles/validator-import-api/molecule/teku/prepare.yml
controls/roles/validator-import-api/molecule/teku/verify.yml
controls/roles/validator-import-api/tasks/main.yml

https://github.com/stereum-dev/ethereum-node/issues/163 
https://github.com/stereum-dev/ethereum-node/issues/90

ADD: Teku validator import API

---

controls/roles/configure-firewall/molecule/default/molecule.yml
controls/roles/configure-updates/molecule/default/molecule.yml
controls/roles/fastsync/molecule/default/molecule.yml
controls/roles/manage-service/molecule/monitor-lighthouse/molecule.yml
controls/roles/manage-service/molecule/monitor-nimbus/molecule.yml
controls/roles/manage-service/molecule/ssv-lighthouse/molecule.yml
controls/roles/manage-service/molecule/ssv-nimbus/molecule.yml
controls/roles/manage-service/molecule/ssv-prysm/molecule.yml
controls/roles/manage-service/molecule/ssv-teku/molecule.yml
controls/roles/manage-service/molecule/start-multiple/molecule.yml
controls/roles/manage-service/molecule/start-stop/molecule.yml
controls/roles/manage-service/molecule/start/molecule.yml
controls/roles/manage-service/molecule/write-start/molecule.yml
controls/roles/setup/molecule/default/molecule.yml
controls/roles/ssv-key-generator/molecule/default/molecule.yml
controls/roles/update-services/molecule/default/molecule.yml
controls/roles/update-stereum/molecule/default/molecule.yml
controls/roles/update-stereum/molecule/override/molecule.yml
controls/roles/validator-import-api/molecule/lighthouse/molecule.yml
controls/roles/validator-import-api/molecule/nimbus/molecule.yml
controls/roles/validator-import-api/molecule/prysm/molecule.yml
controls/roles/validator-import-lighthouse/molecule/default/molecule.yml
controls/roles/validator-import-nimbus/molecule/default/molecule.yml
controls/roles/validator-import-prysm/molecule/default/molecule.yml
controls/roles/validator-import-teku/molecule/default/molecule.yml

FIX: using Ubuntu 22.04 instead of 20.04 for tests

---

controls/roles/validator-import-api/tasks/main.yml

https://github.com/stereum-dev/ethereum-node/runs/6507464088?check_suite_focus=true#step:8:389

FIX: lint syntax error 

---

.github/workflows/test-integration.yml
.github/workflows/test-jest.yml
.github/workflows/test-molecule.yml

FIX: switch github actions to ubuntu 22.04

---

controls/roles/validator-import-api/molecule/nimbus/prepare.yml
controls/roles/validator-import-api/molecule/teku/molecule.yml
controls/roles/validator-import-api/tasks/main.yml

https://github.com/stereum-dev/ethereum-node/runs/6579417532?check_suite_focus=true#step:8:419
https://github.com/stereum-dev/ethereum-node/runs/6579417736?check_suite_focus=true#step:8:293
https://github.com/stereum-dev/ethereum-node/runs/6579417875?check_suite_focus=true#step:8:445
https://github.com/stereum-dev/ethereum-node/runs/6579418066?check_suite_focus=true#step:8:70

FIX: molecule test errors

---

controls/roles/validator-import-api/molecule/nimbus/verify.yml
controls/roles/validator-import-api/molecule/teku/create.yml

https://github.com/stereum-dev/ethereum-node/runs/6590715793?check_suite_focus=true#step:8:499

FIX: api nimbus verify

---

controls/roles/fastsync/molecule/default/prepare.yml

https://github.com/stereum-dev/ethereum-node/issues/210
https://github.com/stereum-dev/ethereum-node/issues/213

FIX: replacing stereum lighthouse image

---

launcher/src/backend/NodeConnection.int.js

tested it locally, should work

FIX: NodeConnection Integration Test

---

controls/roles/manage-service/molecule/start-multiple/prepare.yml
controls/roles/manage-service/molecule/start-multiple/verify.yml
controls/roles/manage-service/molecule/start-stop/prepare.yml
controls/roles/manage-service/molecule/start-stop/verify.yml
controls/roles/manage-service/molecule/start/prepare.yml
controls/roles/manage-service/molecule/start/verify.yml
controls/roles/manage-service/molecule/write-start/converge.yml
controls/roles/manage-service/molecule/write-start/verify.yml

https://github.com/stereum-dev/ethereum-node/issues/210
https://github.com/stereum-dev/ethereum-node/issues/213

FIX: replace stereum images

---

launcher/src/backend/OneClickInstall.js
launcher/src/backend/ethereum-services/PrometheusService.js
launcher/src/backend/ethereum-services/PrometheusService.test.js
launcher/src/background.js
launcher/src/components/UI/node-header/SystemLinks.vue
launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
launcher/src/components/layers/FormSetup.vue
launcher/src/store/getters.js
launcher/src/store/index.js
launcher/src/store/mutations.js

resolves #231 #264 
this only works for grafana and is very basic and ugly,
but i couldn't find a better solution without a total makeover of the vuex store

ADD: grafana link with port tunneling

---

launcher/src/backend/SSHService.js
launcher/src/components/layers/FormSetup.vue

ADD: check for necessary password change

---

README.md

FIX: readme up-to-date

---

launcher/src/backend/ethereum-services/LighthouseBeaconService.int.js
launcher/src/backend/ethereum-services/NimbusBeaconService.int.js
launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
launcher/src/backend/ethereum-services/TekuBeaconService.int.js

I messed up with the conflicts 🙃

FIX: Integration tests

---

controls/roles/update-services/molecule/default/verify.yml
controls/roles/update-services/molecule/single-service/verify.yml
controls/roles/update-services/tasks/main.yml

ADD: docker cleanup after updates #334

---

controls/roles/configure-firewall/tasks/ufw.yaml

resolves #333 
this is the same fix as @pepawel pushed in his PR https://github.com/stereum-dev/ethereum2-ansible/pull/200

FIX: ssh listening ports #333

---

controls/roles/manage-service/files/grafana/nimbus/dashboards/beacon_nodes_Grafana_dashboard.json

https://github.com/stereum-dev/ethereum-node/issues/370

FIX: Nimbus's dashboard

---

launcher/src/backend/OneClickInstall.js
launcher/src/backend/ethereum-services/BloxSSVService.js
launcher/src/backend/ethereum-services/BloxSSVService.test.js
launcher/src/backend/ethereum-services/NimbusBeaconService.js
launcher/src/backend/ethereum-services/NimbusBeaconService.test.js
launcher/src/backend/ethereum-services/PrysmBeaconService.js
launcher/src/backend/ethereum-services/PrysmBeaconService.test.js
launcher/src/backend/ethereum-services/TekuBeaconService.js
launcher/src/background.js
launcher/src/components/UI/click-installation/VueSelect.vue
launcher/src/components/UI/node-header/ServiceLinks.vue
launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
launcher/src/components/UI/services-modal/SsvModal.vue
launcher/src/components/layers/FormSetup.vue
launcher/src/store/ControlService.js
launcher/src/store/clickInstallation.js

ADD: OneClickInstallation of BLOX SSV

---

controls/roles/manage-service/files/grafana/bloxssv/dashboards/ssv-operator-node.json
controls/roles/manage-service/molecule/monitor-bloxssv/converge.yml
controls/roles/manage-service/molecule/monitor-bloxssv/create.yml
controls/roles/manage-service/molecule/monitor-bloxssv/destroy.yml
controls/roles/manage-service/molecule/monitor-bloxssv/molecule.yml
controls/roles/manage-service/molecule/monitor-bloxssv/playbook.yml
controls/roles/manage-service/molecule/monitor-bloxssv/prepare.yml
controls/roles/manage-service/molecule/monitor-bloxssv/verify.yml
controls/roles/manage-service/molecule/monitor-lighthouse/converge.yml
controls/roles/manage-service/molecule/monitor-nimbus/converge.yml
controls/roles/manage-service/molecule/monitor-prysm/converge.yml
controls/roles/manage-service/molecule/monitor-teku/converge.yml
controls/roles/ssv-key-generator/tasks/main.yaml

introduces necessary ansible role for provisioning dashboard for blox ssv #311

ADD: molecule test monitor-bloxssv

---

.github/workflows/test-molecule.yml
controls/defaults/stereum_defaults.yaml
controls/roles/manage-service/molecule/besu/converge.yml
controls/roles/manage-service/molecule/besu/create.yml
controls/roles/manage-service/molecule/besu/destroy.yml
controls/roles/manage-service/molecule/besu/molecule.yml
controls/roles/manage-service/molecule/besu/playbook.yml
controls/roles/manage-service/molecule/besu/prepare.yml
controls/roles/manage-service/molecule/besu/verify.yml
controls/roles/manage-service/molecule/nethermind/converge.yml
controls/roles/manage-service/molecule/nethermind/create.yml
controls/roles/manage-service/molecule/nethermind/destroy.yml
controls/roles/manage-service/molecule/nethermind/molecule.yml
controls/roles/manage-service/molecule/nethermind/playbook.yml
controls/roles/manage-service/molecule/nethermind/prepare.yml
controls/roles/manage-service/molecule/nethermind/verify.yml

resolves: https://github.com/stereum-dev/ethereum-node/issues/315, https://github.com/stereum-dev/ethereum-node/issues/312

ADD: execution clients - Besu, Nethermind

---

.github/workflows/test-molecule.yml
controls/roles/ssv-key-generator/tasks/main.yaml

FIX: molecule github actions, ssv-key-generator config overwrite

---

launcher/src/backend/ValidatorAccountManager.js
launcher/src/backend/ethereum-services/GethService.js
launcher/src/backend/ethereum-services/GrafanaService.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.js
launcher/src/backend/ethereum-services/LighthouseValidatorService.js
launcher/src/backend/ethereum-services/NimbusBeaconService.js
launcher/src/backend/ethereum-services/PrometheusService.js
launcher/src/backend/ethereum-services/PrysmBeaconService.js
launcher/src/backend/ethereum-services/PrysmValidatorService.js
launcher/src/backend/ethereum-services/TekuBeaconService.js
launcher/src/background.js
launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
launcher/src/components/UI/the-staking/KeyTable.vue
launcher/src/components/layers/FormSetup.vue
launcher/src/pages/TheNode.vue
launcher/src/store/ControlService.js

resolves #404 
updated image versions to stereum defaults

UPDATE: Validator Import and Validator Listing

---

launcher/src/background.js
launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
launcher/src/components/UI/the-control/ControlGrid.vue
launcher/src/components/layers/FormSetup.vue
launcher/src/store/ControlService.js
launcher/src/store/services.js

ADD: Start&Stop Service

---

controls/roles/manage-service/files/grafana/nimbus/dashboards/beacon_nodes_Grafana_dashboard.json

fix: https://github.com/stereum-dev/ethereum-node/issues/370
grafana issue: https://github.com/grafana/grafana/issues/10786

FIX: grafana dashboard for nimbus

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/ethereum-services/NimbusBeaconService.js
launcher/src/background.js
launcher/src/components/UI/node-header/IconsNav.vue
launcher/src/store/ControlService.js

ADD: updating Stereum and Services, fix nimbus dashboard

---

README.md

Added Banner to ReadMe; slightly longer project description; minor wording/colour changes. 
Hope you like it!

Minor ReadMe Enhancements

---

launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
launcher/src/components/layers/FormSetup.vue

Fixes a bug which got you stuck in connecting animation when installtaion was interrupted by closing application
(the setup still gets interrupted)

FIX: getting stuck on connecting animation

---

controls/callback_plugins/stereumjson.py

`'  -  '` : Some Ansible task-names include ` - `
`\n>\n`: Prevent wrong data if gathering facts includes `\n\n`

UPDATE: ansible log format

---

launcher/src/backend/ethereum-services/GrafanaService.js

fixes #475 
i just did what the log says 😅
idk if this is a valid solution

FIX: grafana not starting with prysm

---

launcher/src/backend/ethereum-services/GrafanaService.js

My last PR somehow did not fix it although it worked 😅 
I hope it fixes #475 know

FIX: grafana

---

controls/roles/setup/tasks/main.yml
launcher/src/backend/NodeConnection.js

FIX: no overwrite of install path while setup

---

controls/roles/manage-service/molecule/ssv-teku/verify.yml

this should resolve the molecule lint issues for the `manage-service` role

FIX: remove duplication of key "until"

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/NodeConnection.test.js
launcher/src/backend/OneClickInstall.js
launcher/src/backend/SSHService.js
launcher/src/backend/ValidatorAccountManager.js
launcher/src/backend/ethereum-services/NimbusBeaconService.int.js
launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
launcher/src/backend/ethereum-services/TekuBeaconService.int.js
launcher/src/background.js
launcher/src/stereumservice.js

fixes #510 
read up on the mechanics: https://unix.stackexchange.com/questions/175415/forward-function-and-variables-into-sudo-su-user-eof

FIX: supporting sudo user

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/ValidatorAccountManager.js
launcher/src/background.js
launcher/src/components/UI/services-modal/SecretkeyRegister.vue
launcher/src/components/UI/services-modal/SsvModal.vue
launcher/src/store/ControlService.js

ADD: Blox SSV key pair replacement

---

launcher/src/backend/Monitoring.js
launcher/src/backend/ServiceManager.js
launcher/src/background.js
launcher/src/components/UI/node-header/MainNavbar.vue
launcher/src/components/UI/node-manage/NodeConfiguration.vue
launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
launcher/src/components/UI/server-connection/FormSetup.vue
launcher/src/components/UI/the-control/ControlGrid.vue
launcher/src/components/UI/the-node/PluginZone.vue
launcher/src/store/nodeHeader.js

Fixes:
- Services with no specific validator service didn't load correctly
- no more loading of services in `FormSetup.vue` and `VerifyInstallation.vue`
- bugs while deleting config
- and other smaller problems

FIX: many issues

---

.github/workflows/test-molecule.yml
controls/roles/configure-firewall/tasks/packages.yaml

fixes:
- slow install of packages of ufw
- mass test creation of molecule tests -> now in tree structure with dependencies

FIX: Small fixes bundle

---

controls/defaults/stereum_defaults.yaml
controls/roles/manage-service/files/grafana/BloxSSVService/dashboards/ssv-operator-node.json

FIX: update blox ssv to rc.5 + dashboard

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/OneClickInstall.js
launcher/src/background.js
launcher/src/components/UI/node-header/IconsNav.vue
launcher/src/components/UI/node-header/MainNavbar.vue
launcher/src/components/UI/node-header/UpdateModal.vue
launcher/src/store/ControlService.js
launcher/src/store/nodeHeader.js

Installed versions are now compared with versions from [https://stereum.net/downloads/updates.json](https://stereum.net/downloads/updates.json)
When installing, service image versions get pulled from [https://stereum.net/downloads/updates.json](https://stereum.net/downloads/updates.json)

ADD: versions according to api

---

.github/workflows/test-molecule.yml
controls/defaults/stereum_defaults.yaml
controls/roles/manage-service/molecule/notifications/converge.yml
controls/roles/manage-service/molecule/notifications/create.yml
controls/roles/manage-service/molecule/notifications/destroy.yml
controls/roles/manage-service/molecule/notifications/molecule.yml
controls/roles/manage-service/molecule/notifications/playbook.yml
controls/roles/manage-service/molecule/notifications/prepare.yml
controls/roles/manage-service/molecule/notifications/verify.yml
controls/roles/manage-service/tasks/configure-grafana.yml
controls/roles/manage-service/tasks/main.yml
controls/roles/manage-service/tasks/write-grafana-configuration.yml
controls/roles/manage-service/tasks/write-grafana-dashboards.yml

ADD: stereum notifications service

---

controls/roles/manage-service/files/grafana/grafana.ini
controls/roles/manage-service/molecule/monitor-besu/converge.yml
controls/roles/manage-service/molecule/monitor-bloxssv/converge.yml
controls/roles/manage-service/molecule/monitor-geth/converge.yml
controls/roles/manage-service/molecule/monitor-lighthouse/converge.yml
controls/roles/manage-service/molecule/monitor-nethermind/converge.yml
controls/roles/manage-service/molecule/monitor-nimbus/converge.yml
controls/roles/manage-service/molecule/monitor-prysm/converge.yml
controls/roles/manage-service/molecule/monitor-teku/converge.yml
controls/roles/manage-service/molecule/notifications/converge.yml
controls/roles/manage-service/tasks/main.yml
controls/roles/manage-service/tasks/write-grafana-configuration.yml
launcher/src/backend/ethereum-services/GrafanaService.js

FIX: write grafana.ini automatically

---

launcher/src/backend/SSHService.js
launcher/src/background.js
launcher/src/components/UI/node-header/MainNavbar.vue
launcher/src/components/UI/the-staking/KeyTable.vue
launcher/src/store/ControlService.js

closes #560 
and some smaller problems

ADD: auto reconnect after connection loss

---

launcher/src/backend/Monitoring.js
launcher/src/backend/NodeConnection.js
launcher/src/backend/OneClickInstall.js
launcher/src/backend/TaskManager.js
launcher/src/background.js
launcher/src/components/UI/node-header/IconsNav.vue
launcher/src/components/UI/node-header/MainNavbar.vue
launcher/src/components/UI/node-manage/NodeConfiguration.vue
launcher/src/components/UI/server-connection/FormSetup.vue
launcher/src/components/UI/the-control/MachineName.vue
launcher/src/components/UI/the-control/TheCpu.vue
launcher/src/components/UI/the-control/TheHard.vue
launcher/src/components/UI/the-control/TheNetwork.vue
launcher/src/components/UI/the-control/TheRam.vue
launcher/src/components/UI/the-node/JournalNode.vue
launcher/src/pages/TheControl.vue
launcher/src/store/theControl.js

fixes #525 
it worked 10 times in a row but idk why #588 (just to have a reference)
Stereum version is now pulled on setup (if api fails or IS_DEV=true: main HEAD )
also fixed some smaller problems

REFACTOR: monitoring on Control-Page

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/ethereum-services/TekuBeaconService.js
launcher/src/background.js
launcher/src/components/UI/the-control/ControlGrid.vue
launcher/src/components/UI/the-node/NodeService.vue
launcher/src/components/UI/the-node/TheExpert.vue
launcher/src/components/UI/the-staking/KeyTable.vue
launcher/src/store/ControlService.js
launcher/src/store/services.js

fixes #348 
fixes #335
fixes #466 
fixes #595
fixes #585

ADD: functionality for Expert Mode

---

launcher/src/backend/OneClickInstall.js
launcher/src/backend/ethereum-services/BesuService.js
launcher/src/backend/ethereum-services/BesuService.test.js
launcher/src/backend/ethereum-services/GethService.js
launcher/src/backend/ethereum-services/GethService.test.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.test.js
launcher/src/backend/ethereum-services/LighthouseValidatorService.js
launcher/src/backend/ethereum-services/NethermindService.js
launcher/src/backend/ethereum-services/NethermindService.test.js
launcher/src/backend/ethereum-services/PrysmBeaconService.js
launcher/src/backend/ethereum-services/PrysmBeaconService.test.js
launcher/src/backend/ethereum-services/PrysmValidatorService.js
launcher/src/backend/ethereum-services/TekuBeaconService.js
launcher/src/backend/ethereum-services/TekuBeaconService.test.js
launcher/src/components/UI/the-staking/KeyTable.vue

These changes need the changes of #573 and updated [versions](https://stereum.net/downloads/updates.json) to work

ADD: JS Backend The Merge support

---

controls/defaults/stereum_defaults.yaml
controls/roles/manage-service/molecule/besu-teku/converge.yml
controls/roles/manage-service/molecule/besu-teku/create.yml
controls/roles/manage-service/molecule/besu-teku/destroy.yml
controls/roles/manage-service/molecule/besu-teku/molecule.yml
controls/roles/manage-service/molecule/besu-teku/playbook.yml
controls/roles/manage-service/molecule/besu-teku/prepare.yml
controls/roles/manage-service/molecule/besu-teku/verify.yml
controls/roles/manage-service/molecule/nethermind-teku/converge.yml
controls/roles/manage-service/molecule/nethermind-teku/create.yml
controls/roles/manage-service/molecule/nethermind-teku/destroy.yml
controls/roles/manage-service/molecule/nethermind-teku/molecule.yml
controls/roles/manage-service/molecule/nethermind-teku/playbook.yml
controls/roles/manage-service/molecule/nethermind-teku/prepare.yml
controls/roles/manage-service/molecule/nethermind-teku/verify.yml

- Besu + Teku
- Nethermind +Teku

ADD: Molecule test merge support

---

launcher/src/backend/StringUtils.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.int.js
launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
launcher/src/backend/ethereum-services/TekuBeaconService.int.js

integration tests wont get stuck (will still fail except of Teku)
replaced math.random with crypto (more random)

UPDATE: Integration tests, replace Math.random with crypto

---

launcher/src/backend/ethereum-services/LighthouseValidatorService.js
launcher/src/backend/ethereum-services/NimbusBeaconService.js
launcher/src/backend/ethereum-services/PrysmValidatorService.js
launcher/src/backend/ethereum-services/TekuBeaconService.js
launcher/src/components/UI/the-node/TheExpert.vue
launcher/src/store/services.js

there is now an option on the mouseover menu to change the fee recipient

ADD: fee recipient option to validator services

---

controls/roles/manage-service/files/grafana/BesuService/dashboards/besu-overview_rev5.json
controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/BeaconProcessing.json
controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Database.json
controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/ForkChoice.json
controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Slasher.json
controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Summary.json
controls/roles/manage-service/files/grafana/LighthouseBeaconService/dashboards/Sync.json
controls/roles/manage-service/files/grafana/LighthouseValidatorService/dashboards/ValidatorClient.json
controls/roles/manage-service/files/grafana/LighthouseValidatorService/dashboards/ValidatorMonitor.json
controls/roles/manage-service/files/grafana/NethermindService/dashboards/nethermind.json
controls/roles/manage-service/files/grafana/NimbusBeaconService/dashboards/beacon_nodes_Grafana_dashboard.json
controls/roles/manage-service/files/grafana/TekuBeaconService/dashboards/teku_single.json

FIX: issues with various dashboards

---

controls/defaults/stereum_defaults.yaml
controls/roles/manage-service/molecule/monitor-ssvnetwork/prepare.yml
controls/roles/manage-service/molecule/ssv-lighthouse/converge.yml
controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
controls/roles/manage-service/molecule/ssv-nimbus/converge.yml
controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
controls/roles/manage-service/molecule/ssv-prysm/converge.yml
controls/roles/manage-service/molecule/ssv-prysm/verify.yml
controls/roles/manage-service/molecule/ssv-teku/converge.yml
controls/roles/manage-service/molecule/ssv-teku/verify.yml
controls/roles/ssv-key-generator/molecule/default/converge.yml
controls/roles/ssv-key-generator/tasks/main.yaml
launcher/src/backend/ValidatorAccountManager.js
launcher/src/backend/ethereum-services/SSVNetworkService.js
launcher/src/backend/ethereum-services/SSVNetworkService.test 2.js
launcher/src/backend/ethereum-services/SSVNetworkService.test.js
launcher/src/components/UI/services-modal/SsvModal.vue

adjusting domains to match changes of ssv network testnet domains

FIX: adjust ssv network shifu domains

---

launcher/src/backend/NodeConnection.js

FIX: make sure to install git on setup

---

launcher/src/components/UI/node-header/MainNavbar.vue
launcher/src/components/UI/node-header/UpdatePanel.vue

disable update button/icon if no update avail

---

launcher/src/components/UI/node-header/SupportModal.vue
launcher/src/components/UI/node-header/UpdatePanel.vue
launcher/src/components/UI/the-node/TheExpert.vue

Update panel Stereum btn fixed
update panel ALL btn fixed
Github link changed for support modal
active Confirm btn after any changes in setting

FIX: update & setting issues

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/SSHService.js
launcher/src/background.js
launcher/src/components/layers/InstallitionMenu.vue
launcher/src/store/ControlService.js

check for correct sudo permissions and tiny tweaks

---

controls/roles/manage-service/files/grafana/PrometheusNodeExporterService/dashboards/node_exporter_full.json

ADD: prometheus node exporter full dashboard

---

launcher/src/backend/StringUtils.js
launcher/src/backend/ValidatorAccountManager.js
launcher/src/components/UI/node-manage/NodeConfiguration.vue

fixes #447 the issue was a different response data structure
fixes #716
also added a redirection to the login page after destroying aka nuking a node

FIX: no error msg on failed validator import

---

launcher/src/components/UI/node-header/IconsNav.vue
launcher/src/components/UI/node-header/UpdatePanel.vue

#730 
I'm pretty sure this bug is caused by errors interrupting the refresh flow.
these changes should prevent this from happening.
But i wasn't able to reproduce this bug so i wont close this issue yet.

FIX: update btns getting stuck

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/SSHService.js
launcher/src/background.js
launcher/src/components/UI/node-header/IconsNav.vue
launcher/src/store/ControlService.js

all tunnels are closed on logout fixes #687
all states are reset after logout fixes #726 and other glitchy behaviour after logout

ADJUST: Logout

---

launcher/src/backend/ethereum-services/TekuBeaconService.js

https://docs.teku.consensys.net/en/latest/Reference/CLI/CLI-Syntax/#metrics-categories

FIX: teku metrics to default (all categories)

---

controls/finishUpdate.yaml
controls/roles/update-changes/.yamllint
controls/roles/update-changes/molecule/20-rc3/converge.yml
controls/roles/update-changes/molecule/20-rc3/molecule.yml
controls/roles/update-changes/molecule/20-rc3/playbook.yml
controls/roles/update-changes/molecule/20-rc3/prepare.yml
controls/roles/update-changes/molecule/20-rc3/verify.yml
controls/roles/update-changes/tasks/2.0-rc3/fix-graffiti-738.yaml
controls/roles/update-changes/tasks/2.0-rc3/updates-20-rc3.yaml
controls/roles/update-changes/tasks/main.yml
controls/roles/update-changes/tests/test.yml

this updates existing service configurations to be fully compatible with #737 and #738

ADD: (tests for) config update #738 #737

---

launcher/package-lock.json
launcher/package.json
launcher/src/background.js

This adds launcher updates in the background without any dialogs atm.
Updater-Activities are logged via `electron-log`

ADD: launcher updates

---

launcher/src/components/UI/the-staking/DisplayValidators.vue
launcher/src/components/UI/the-staking/InsertValidator.vue

fixes #705
Import button not clickable and drag and drop disabled while there is no running validator service

FIX: Prevent listing and importing on non running services

---

controls/defaults/stereum_defaults.yaml

Prysm: https://github.com/prysmaticlabs/prysm/releases/tag/v3.1.1

UPDATE: prysm docker image

---

launcher/src/backend/Monitoring.js
launcher/src/background.js
launcher/src/pages/TheControl.vue
launcher/src/store/ControlService.js

Data for wiring syncstatus (#601) and p2pstatus on controls page

ADD: nodestats data syncstatus and p2pstatus

---

launcher/src/backend/Monitoring.js

Hotfix to avoid service errors on controls page

FIX: make sure names property exists

---

launcher/src/backend/ValidatorAccountManager.js

Nimbus doesn't support a graffiti file
so i implemted it via the rest api of Nimbus [DOCs](https://nimbus.guide/rest-api.html)

ADD: changeable graffiti for nimbus

---

launcher/src/backend/NodeConnection.js
launcher/src/background.js
launcher/src/components/UI/node-header/IconsNav.vue
launcher/src/store/ControlService.js

1. run `update-stereum` role (`IS_DEV=true` -> pulling from main HEAD)
2. if `update-stereum` successfull -> run `update-changes` role
3. run `update-services` role
1. run `update-stereum` role (`IS_DEV=true` -> pulling from main HEAD)
2. if `update-stereum` successfull -> run `update-changes` role

ADJUST: Updates

---

launcher/src/backend/ethereum-services/BesuService.int.js
launcher/src/backend/ethereum-services/GethService.int.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.int.js
launcher/src/backend/ethereum-services/MevboostService.int.js
launcher/src/backend/ethereum-services/NethermindService.int.js
launcher/src/backend/ethereum-services/NimbusBeaconService.int.js
launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
launcher/src/backend/ethereum-services/TekuBeaconService.int.js

Add a loop for retrieving logs so tests don't fail because of not long enough logs.

ADJUST: Integration Tests

---

launcher/src/backend/Monitoring.js
launcher/src/pages/TheControl.vue

Data for storage status of the controls page component

ADD: nodestats data for storagestatus

---

launcher/src/backend/NodeConnection.js

the timescope variable wasn't passed correctly

FIX: restart services role

---

launcher/src/backend/Monitoring.js
launcher/src/components/UI/the-control/SyncStatus.vue
launcher/src/pages/TheControl.vue

Changed nodestats response structure.
Each data element has now its own return code/info/data fields to improve error handling.
Adjusted icon and lower/higher output in syncstatus component

REFACTOR: wiring tweaks

---

launcher/src/backend/Monitoring.js

Provides storage status for all services.
GETH labels for Prometheus in getSyncStatus now verified.

FIX: storage status and and geth labels

---

launcher/src/backend/Monitoring.js

All storage elements now have correct values.

FIX: correct value for last storage element

---

launcher/src/backend/NodeConnection.js
launcher/src/components/UI/the-node/TheExpert.vue

FIX: changes not applied, expand restart time scope

---

launcher/src/backend/Monitoring.js

After resolving a merge conflict online the style of monitoring.js is now changed back to normal.

STYLE: monitoring.js back to normal

---

controls/stereum-services-update.sh

molecule test should work after releasing the next version

FIX: restart services after unattended update

---

launcher/src/backend/OneClickInstall.js
launcher/src/backend/ethereum-services/NethermindService.js

FIX: nethermind sync

---

controls/roles/update-changes/molecule/20-rc6/converge.yml
controls/roles/update-changes/molecule/20-rc6/molecule.yml
controls/roles/update-changes/molecule/20-rc6/playbook.yml
controls/roles/update-changes/molecule/20-rc6/prepare.yml
controls/roles/update-changes/molecule/20-rc6/verify.yml
controls/roles/update-changes/tasks/2.0-rc6/adjust-ports-814.yaml
controls/roles/update-changes/tasks/2.0-rc6/fix-prysm-822.yaml
controls/roles/update-changes/tasks/2.0-rc6/updates-20-rc6.yaml
controls/roles/update-changes/tasks/main.yml

This PR includes update changes ansible roles for PRs: #814 #822

ADD: Update Changes for RC6

---

launcher/src/backend/ServiceManager.js
launcher/src/backend/ethereum-services/ErigonService.int.js
launcher/src/backend/ethereum-services/ErigonService.js
launcher/src/backend/ethereum-services/ErigonService.test.js
launcher/src/backend/ethereum-services/LodestarBeaconService.int.js
launcher/src/backend/ethereum-services/LodestarBeaconService.js
launcher/src/backend/ethereum-services/LodestarBeaconService.test.js
launcher/src/backend/ethereum-services/LodestarValidatorService.js
launcher/src/backend/ethereum-services/LodestarValidatorService.test.js

part of: https://github.com/stereum-dev/ethereum-node/issues/660, https://github.com/stereum-dev/ethereum-node/issues/385

ADD: erigon, lodestar - js backend

---

launcher/package-lock.json
launcher/package.json
launcher/src/App.vue
launcher/src/backend/Monitoring.js
launcher/src/background.js
launcher/src/components/UI/the-node/PluginLogs.vue
launcher/src/components/UI/the-node/PluginZone.vue
launcher/src/pages/TheNode.vue
launcher/src/store/ControlService.js
launcher/src/store/theNode.js
launcher/vue.config.js

ADD:Plugins logs 

---

launcher/src/background.js

Follow expected Desktop Application behaviour and avoid common style issues.

REFACTOR: disable window refresh and menu items in build

---

launcher/src/backend/OneClickInstall.js
launcher/src/backend/ServiceManager.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.int.js
launcher/src/backend/ethereum-services/LighthouseBeaconService.js
launcher/src/backend/ethereum-services/LodestarBeaconService.int.js
launcher/src/backend/ethereum-services/LodestarBeaconService.js
launcher/src/backend/ethereum-services/LodestarBeaconService.test.js
launcher/src/backend/ethereum-services/LodestarValidatorService.js
launcher/src/backend/ethereum-services/NimbusBeaconService.int.js
launcher/src/backend/ethereum-services/NimbusBeaconService.js
launcher/src/backend/ethereum-services/NodeService.js
launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
launcher/src/backend/ethereum-services/PrysmBeaconService.js
launcher/src/backend/ethereum-services/TekuBeaconService.int.js
launcher/src/backend/ethereum-services/TekuBeaconService.js

MevBoost integration caused some issues with the OneClickInstallation

FIX: OneClickInstallation and Client Tests

---

.github/workflows/test-molecule.yml
controls/roles/update-changes/molecule/20-rc7/converge.yml
controls/roles/update-changes/molecule/20-rc7/molecule.yml
controls/roles/update-changes/molecule/20-rc7/playbook.yml
controls/roles/update-changes/molecule/20-rc7/prepare.yml
controls/roles/update-changes/molecule/20-rc7/verify.yml
controls/roles/update-changes/tasks/2.0-rc7/updates-20-rc7.yaml
controls/roles/update-changes/tasks/main.yml
launcher/src/backend/ethereum-services/NodeService.js

error prone for missing dependencies,
update-changes script for mevboost dependency

ADD: mevboost dep script

---

controls/roles/update-changes/molecule/20-rc7/prepare.yml
controls/roles/update-changes/molecule/20-rc7/verify.yml
controls/roles/update-changes/tasks/2.0-rc7/add-mevboost-dependency.yaml
controls/roles/update-changes/tasks/2.0-rc7/updates-20-rc7.yaml
launcher/src/backend/ethereum-services/BesuService.js

removed `--Xmerge-support`
and created ansible update script for existing nodes
fixes #873

REMOVE: deprecated besu attribute

---

controls/roles/update-stereum/molecule/full/prepare.yml
controls/roles/update-stereum/molecule/full/verify.yml

This fixes an issue with the molecule test `full` of role `update-stereum`.

FIX: molecule test update-stereum full

---

README.md

overhaul of the main readme for this repo

FIX: refresh readme

---

controls/defaults/stereum_defaults.yaml

FIX: docker image version typo

---

launcher/src/backend/Monitoring.js
launcher/src/background.js

- Clears monitoring cache on logout
- Combines monitoring logout tasks

REFACTOR: fix cache and combine monitoring logout tasks 

---

controls/roles/manage-service/molecule/erigon-lodestar/converge.yml
controls/roles/manage-service/molecule/erigon-lodestar/verify.yml
controls/roles/update-stereum/molecule/default/converge.yml
controls/roles/update-stereum/molecule/default/verify.yml
controls/roles/validator-delete-api/molecule/lodestar/verify.yml
controls/roles/validator-fee-recipient-api/molecule/lodestar/verify.yml
controls/roles/validator-import-api/molecule/lodestar/verify.yml
controls/roles/validator-list-api/molecule/lodestar/verify.yml
launcher/src/backend/ethereum-services/ErigonService.js

This should fix the failing molecule tests

UPDATE: Molecule Tests

---

launcher/src/backend/ethereum-services/NethermindService.js

forgot to change the bootnodes for nethermind too

FIX: Bootnodes for nethermind

---

controls/roles/manage-service/molecule/nimbus-checkpoint-sync/converge.yml
controls/roles/manage-service/molecule/nimbus-checkpoint-sync/create.yml
controls/roles/manage-service/molecule/nimbus-checkpoint-sync/destroy.yml
controls/roles/manage-service/molecule/nimbus-checkpoint-sync/molecule.yml
controls/roles/manage-service/molecule/nimbus-checkpoint-sync/playbook.yml
controls/roles/manage-service/molecule/nimbus-checkpoint-sync/prepare.yml
controls/roles/manage-service/molecule/nimbus-checkpoint-sync/verify.yml
controls/roles/manage-service/tasks/main.yml
controls/roles/manage-service/tasks/nimbus-checkpoint-sync.yml
controls/roles/validator-delete-api/molecule/teku/prepare.yml
controls/roles/validator-list-api/molecule/teku/prepare.yml

fixes #683
fixes #624
Also adjusts some molecule tests

ADD: Checkpoint Sync for Nimbus

---

launcher/src/store/nodeManage.js

Added:
`Ultrasound money`
`Aestus`
`Agnostic`

ADD: Testnet Relays

---

launcher/src/background.js

Window size did not adjust in development mode on Windows

FIX: windows development window size

---

launcher/src/store/nodeManage.js

Looking forward to the mainnet relay being added too :)
`https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money`

minor cosmetic change to relay name

---

launcher/src/components/UI/node-manage/SidebarManage.vue

Fixed by adding a function to cycle backward

FIX: Arrow-Buttons on 'Edit Node' for services don't cycle

---

launcher/src/components/UI/the-staking/DisplayValidators.vue

This adds basic validator stats on gnosis fetched very epoch from [https://beacon.gnosischain.com/](https://beacon.gnosischain.com/)

ADD: gnosis basic validator stats

---

launcher/src/backend/Monitoring.js

This implements Lodestar to SyncStatus, P2PStatus and DATA-API Widgets.

REFACTOR: Add Lodestar CL to Dashboard Widgets

---

launcher/src/backend/ServiceManager.js
launcher/src/components/UI/node-header/MainNavbar.vue
launcher/src/components/UI/node-manage/AddPanel.vue
launcher/src/components/UI/node-manage/ModifyPanel.vue
launcher/src/components/UI/services-modal/MevboostModal.vue
launcher/src/store/nodeManage.js

Adjusting prometheus port binding via custom installation broke the config.
Cencorship -> Censorship
- Aestus Mainnet
- Agnostic Mainnet
- Eden Testnet and Mainnet
- Relayooor's Mainnet

FIX: Custom Port issues, typoes and added relays

---

launcher/src/backend/NodeConnection.js

FIX: destroyNode crashing without parameter

---

controls/roles/manage-service/tasks/main.yml

Related to issues with shutting down Geth gracefully. Also mentioned here: https://www.reddit.com/r/ethstaker/comments/10wg4py/how_to_terminate_gracefully_geth_syncing_in/

FIX: grace period for stopping services adapted

---

launcher/src/components/UI/node-manage/AddPanel.vue
launcher/src/components/UI/node-manage/ModifyPanel.vue
launcher/src/components/UI/services-modal/MevboostModal.vue

Resolved issues with the display of tooltips in Mevboost by thoroughly checking the code and implementing necessary fixes. The tooltips now display correctly and provide accurate information to users.

Fix tooltips debug for Mevboost

---

launcher/src/components/UI/the-control/SyncStatus.vue

Re-design of the SyncStatus widget as described in #673

REFACTOR: re-design syncstatus widget

---

launcher/src/components/UI/the-control/PeerToPeer.vue

Prevent errors if the data property is missing in p2pstatus widget

FIX: check data proterty in p2pstatus widget

---

launcher/src/backend/SSHService.js
launcher/src/components/UI/server-connection/FormSetup.vue
launcher/src/store/ControlService.js

Added option to use SSH Key with passphrase

Added SSH Key Authentication with passphrase

---

controls/roles/manage-service/files/grafana/TekuBeaconService/dashboards/teku_rev7.json
launcher/src/backend/SSHService.js
launcher/src/components/UI/server-connection/FormSetup.vue
launcher/src/store/ControlService.js

Updated Teko Grafana dashboard

Dashboard update

---

launcher/src/backend/Monitoring.js
launcher/src/components/UI/the-staking/DisplayValidators.vue

validator states from beacon-API: add "active since"

ADD: validator state -> active since

---

launcher/src/backend/ValidatorAccountManager.js

Fixes couple issues with the new validator handling
https://github.com/stereum-dev/ethereum-node/issues/997

FIX: issues for release

---

launcher/src/backend/Monitoring.js

- Fixes #1090
- From now on get current block via RPC, and head block via Beacon API to show correct sync staus for Erigon.
- This is also possible for all other clients (if needed but currently disabled)

FIX: Erigon sync status

---

launcher/src/components/UI/services-modal/RegisterSsv.vue
launcher/src/components/UI/services-modal/SecretkeyRegister.vue
launcher/src/components/UI/services-modal/SsvDashboard.vue

This fixes the current issues with on the ssv modal

FIX: SSV Modal

---

README.md
launcher/CONTRIBUTING.md

- Basic guidelines for contributing to Stereum

DOCS: add contribution guide

---

.vscode/settings.json
launcher/src/backend/NodeConnection.js
launcher/src/components/UI/node-manage/NodeConfiguration.vue
launcher/src/components/UI/node-manage/RemoveModal.vue

- Shows main tasks that happen in the background while a node is nuked
- Part of #1037 - requires frontend style adjustments

REFACTOR: show log during nuke node process

---

launcher/public/output.css
launcher/src/components/UI/plugin-installation/InstallingAnimation.vue
launcher/src/components/UI/task-manager/TaskManager.vue
launcher/src/components/UI/the-node/PluginLogs.vue
launcher/src/store/clickInstallation.js

- Latest fixes for tasks in custom install animation

FIX: tasks on animation

---

launcher/src/backend/Monitoring.js

FIX: Remove Prometheus NE from used storage list

---

launcher/src/backend/NodeConnection.test.js
launcher/src/backend/SSHService.js
launcher/src/backend/ServiceManager.test.js
launcher/src/backend/ValidatorAccountManager.js
launcher/src/backend/ethereum-services/FlashbotsMevBoostService.int.js
launcher/src/backend/ethereum-services/FlashbotsMevBoostService.js
launcher/src/backend/ethereum-services/NimbusBeaconService.int.js

MEV-Boost Service logs are now logged in `stdout` instead od `stderr` (Implementation of some kind of redundancy i nthe future?)

FIX: Tests and ESLint issues

---

launcher/src/components/UI/the-node/JournalNode.vue

FIX: Stereum Notifier takes very long to stop

---

launcher/src/backend/ServiceManager.js
launcher/src/components/UI/the-node/JournalNode.vue
launcher/src/components/UI/the-node/ResyncSeparateServices.vue

Added option to resync a service from genesis or perform checkpoint sync

Resync clients

---

launcher/src/components/UI/the-staking/DisplayValidators.vue
launcher/src/components/UI/the-staking/SelectionOptions.vue
launcher/src/components/UI/the-staking/StakingGrid.vue

fixed `Graffiti` and `Remove All Keys` Buttons

FIX: Buttons on Staking Page

---

launcher/package.json

Reverts stereum-dev/ethereum-node#1175

Revert "FIX: update version"

---

launcher/src/backend/ServiceManager.js

FIX: mev-boost custom installation

---

launcher/src/backend/NodeConnection.js
launcher/src/backend/ValidatorAccountManager.js

Prysm keystore permissions are now updated on every Keymanager API interaction
Added better error handling

ADD: better error handling, prysm adjustments

---

launcher/src/backend/Monitoring.js
launcher/src/background.js
launcher/src/components/UI/the-control/TheStorage.vue
launcher/src/pages/TheControl.vue
launcher/src/store/ControlService.js

Improved loading speed for most of the dashboard widgets.

REFACTOR: improve dashboard loading speed

---

controls/roles/update-changes/molecule/20-rc12/molecule.yml
controls/roles/update-changes/molecule/20-rc16/verify.yml
controls/roles/update-changes/molecule/20-rc18/converge.yml
controls/roles/update-changes/molecule/20-rc18/molecule.yml
controls/roles/update-changes/molecule/20-rc18/playbook.yml
controls/roles/update-changes/molecule/20-rc18/prepare.yml
controls/roles/update-changes/molecule/20-rc18/verify.yml
controls/roles/update-changes/tasks/2.0-rc18/erigon_changes_1200.yaml
controls/roles/update-changes/tasks/2.0-rc18/updates-20-rc18.yaml
controls/roles/update-changes/tasks/2.0-rc18/ws_endpoint_mappings_1203.yaml
controls/roles/update-changes/tasks/main.yml
launcher/src/backend/ServiceManager.js

Added scripts for the following changes:
- WS Tunnel Widget (Port Mapping for all EC)
- Erigon `--externalcl` removal
- Erigon `--prune=htc` changed to `--prune=default`
fixes #1200 
fixes #1203

ADD: Update Changes Scripts

---

controls/roles/manage-service/tasks/write-graffiti-files.yml
launcher/src/backend/ethereum-services/GethService.js

FIX: Teku graffiti, Geth db for new setups

---

launcher/src/components/UI/the-node/TutorialGuide.vue

Softlock in Integrated Tutorial #1250

fix Softlock in Integrated Tutorial fix#1250

---

launcher/src/components/UI/the-node/NodeAlert.vue

FIX: remove unnecessary error handling

---

controls/roles/update-stereum/tasks/main.yml
launcher/src/backend/ethereum-services/ServicePort.js

FIX: port mapping and stereum update bug

---

launcher/src/backend/ServiceManager.js
launcher/src/background.js
launcher/src/components/UI/the-node/JournalNode.vue
launcher/src/components/UI/the-node/TheExpert.vue
launcher/src/store/ControlService.js

Services automatically restarts to apply changes after confirming them

ADD: Restart service on confirmed changes

---

launcher/src/components/UI/plugin-installation/ConsensusSync.vue

Show correct recommended checkpoints

---

launcher/src/backend/Monitoring.js
launcher/src/background.js
launcher/src/components/UI/the-control/TheBalance.vue
launcher/src/languages/en.json
launcher/src/pages/TheControl.vue
launcher/src/store/ControlService.js
launcher/src/store/theControl.js

- Implemented Balance widget backend code
- Added core code for front-end wiring

REFACTOR: balance widget backend and wiring core

---

launcher/src/components/UI/the-staking/GrafitiMultipleValidators.vue

FIX: Limit graffiti length to 32

---

launcher/src/backend/ServiceManager.js

Clients now get unique ports mapped to them

FIX: Identical Port Mapping

---

.github/workflows/lint.yml
.vscode/settings.json
controls/roles/update-changes/molecule/20-rc20/converge.yml
controls/roles/update-changes/molecule/20-rc20/create.yml
controls/roles/update-changes/molecule/20-rc20/destroy.yml
controls/roles/update-changes/molecule/20-rc20/molecule.yml
controls/roles/update-changes/molecule/20-rc20/playbook.yml
controls/roles/update-changes/molecule/20-rc20/prepare.yml
controls/roles/update-changes/molecule/20-rc20/verify.yml
controls/roles/update-changes/tasks/2.0-rc20/updates-20-rc20.yaml
controls/roles/update-changes/tasks/2.0-rc20/web3signer_new_db_schema.yaml
controls/roles/update-changes/tasks/main.yml
launcher/src/backend/NodeConnection.js
launcher/src/backend/ServiceManager.js
launcher/src/components/UI/node-manage/AddPanel.vue
launcher/src/components/UI/node-manage/ModifyPanel.vue
launcher/src/components/UI/the-control/PortList.vue
launcher/src/components/UI/the-control/TheStorage.vue

Added update script for web3signer 23.3.0 and higher
Added ESLint Github workflow

ADD: web3signer update changes, lint workflow, smaller fixes

---

launcher/src/components/UI/node-header/MainNavbar.vue
launcher/src/components/UI/the-control/ControlAlert.vue
launcher/src/components/UI/the-node/NodeAlert.vue

set the icon of installed service for the service update notification in the alarm boxes

fix update notification with icon and version

---

launcher/src/components/UI/the-control/ControlAlert.vue
launcher/src/components/UI/the-control/DataApi.vue
launcher/src/components/UI/the-control/RpcEndpoint.vue
launcher/src/components/UI/the-control/WsEndpoint.vue
launcher/src/components/UI/the-node/NodeAlert.vue
launcher/src/store/nodeHeader.js

warning alarm shows when RPC, data API and WS points are open in the alarm boxes

fix the ports point warning status 

---

launcher/src/backend/Monitoring.js
launcher/src/components/UI/plugin-installation/ConsensusSync.vue

- ensures curl is installed for checkpoint availability check
- if curl is for whatever reason not installable all checkpoints considered as available
- fixes #1365

FIX: ensure curl for checkpoint availability check

---

launcher/src/backend/Monitoring.js
launcher/src/background.js
launcher/src/components/UI/node-manage/DropZone.vue
launcher/src/components/UI/the-control/EpochSlot.vue
launcher/src/components/UI/the-control/TheStaking.vue
launcher/src/store/ControlService.js

part of: https://github.com/stereum-dev/ethereum-node/issues/673

Current Epoch and Slot on the control tab

---

controls/roles/manage-service/tasks/main.yml

Added Reth Service to main.yml for testing

ADD: Reth Preparation

---

launcher/src/backend/ethereum-services/NethermindService.int.js
launcher/src/background.js
launcher/src/components/UI/the-staking/ValidatorStats.vue

changed log outputs caused them to fail
Dev console was flooded with warnings
This was actually intentionally as the handler on error would open this dialog window.
changed this behaviour now to console only

FIX: Couple Smaller Issues

---

launcher/src/components/UI/the-control/AmsterdamComponent.vue
launcher/src/components/UI/the-control/EpochSlot.vue

One Epoch contains 32 Slots. These Slots are in this component, visualized by the square. A slot can be attested (green) or missed (red) by the network participants. This is the chain's view.
issue: https://github.com/stereum-dev/ethereum-node/issues/673

Redesign the Network and Node Component in the control tab

---

launcher/src/components/UI/the-control/AmsterdamComponent.vue

debugging the counting in Amsterdam Comp.

---

launcher/src/components/UI/the-control/AmsterdamComponent.vue

Reduced additional logs for error handling

fix the error Handling for the ams. comp.

---

launcher/src/backend/NodeConnection.js
launcher/src/background.js
launcher/src/components/UI/the-node/TheExpert.vue
launcher/src/store/ControlService.js

When applying changes to prometheus configuration, it now adds 'overwrite: false' to prevent automatic overwrite

ADD: customizable prometheus configuration

---

launcher/src/backend/Monitoring.js
launcher/src/components/UI/the-control/AmsterdamComponent.vue

issue: https://github.com/stereum-dev/ethereum-node/issues/673
Status of slot(s) which are belonging to current, justified and finalized epochs (backend), also frontend:)

ADD: current slot status in backend

---

controls/roles/update-changes/molecule/20-rc16/prepare.yml
controls/roles/update-changes/tasks/2.0-rc16/prometheus_data_retention_1168.yaml
launcher/src/backend/SSHService.js

First Step of #1003
Also fixed data retention getting overwritten with update.
So this PR adds functions for:
- changing password
- generating SSH Keys
- reading SSH Keys
- writing SSH Keys

ADD: SSH Features

---

launcher/src/backend/Monitoring.js

EDIT: if statement

---

launcher/src/backend/Monitoring.js

previous justified epoch status
issue: https://github.com/stereum-dev/ethereum-node/issues/673

previous justified epoch status

---

launcher/src/backend/ethereum-services/LodestarBeaconService.int.js
launcher/src/backend/ethereum-services/TekuBeaconService.int.js

Logging for Teku and Lodestar changed

FIX: Failing Integration Tests

---

launcher/src/backend/OneClickInstall.js
launcher/src/components/UI/plugin-installation/PluginName.vue

Reth can now be used as a Full Node with the stacking option in the one click installation

ADD: Reth Full Node

---

controls/roles/ssv-key-generator/tasks/main.yaml
launcher/src/backend/ethereum-services/SSVNetworkService.js
launcher/src/components/UI/the-node/TheExpert.vue

Also fixed apply and restart bug.

FIX: SSV Key Gem and Config

---

launcher/src/components/UI/server-connection/FormSetup.vue
launcher/src/components/UI/server-connection/IpScanModal.vue
launcher/src/languages/en.json

update the language JSON for the internationalization

---

launcher/src/components/UI/task-manager/SubTasks.vue
launcher/src/components/UI/task-manager/TaskManager.vue
launcher/src/components/UI/the-node/TheExpert.vue
launcher/src/store/taskManager.js

This PR reverts #1453 because it causes Subtasks Details do close instantly on opening them.
This PR also reverts #1394 because it broke Geth Pruning.

FIX: Pruning and Subtasks

---

launcher/src/components/UI/the-node/TheExpert.vue

checking ip input on expert option

EDIT: checking ip input

---

launcher/src/components/UI/the-node/TheExpert.vue

EDIT: revert ip input check

---

.github/workflows/electron.yaml
launcher/package.json
launcher/vue.config.js

PR for changing our buildscipt + deps

Ci changes

---

launcher/public/output.css
launcher/src/backend/ServiceManager.js
launcher/src/components/UI/edit-page/components/drawer/DrawerFilter.vue
launcher/src/components/UI/node-page/sections/ExpertWindow.vue
launcher/src/composables/services.js
launcher/src/composables/validators.js

This PR is part if the merge checks
Fixes the Custom Installation of SSV and the Mainnet integration. #1402
Also fixes the restart service behaviour. #1434

FIX: SSV Custom Installation, restart services

---

launcher/src/backend/NodeConnection.js
launcher/src/components/UI/node-page/sections/ExpertWindow.vue

on the expert mode needs some UI improvement @mabasian (same as what we did on old one)

editing external ip and port, also doppelganger protection for new UI

---

launcher/src/backend/ethereum-services/SSVNetworkService.js

FIX: SSV Ports

---

launcher/public/output.css
launcher/src/components/UI/the-staking/ValidatorStats.vue

I reverted the Validator Stats to the state before the big UI changes.

FIX: Validator Stats

---

launcher/public/output.css
launcher/src/components/UI/one-click/sections/AnimationSection.vue
launcher/src/components/UI/the-staking/SelectionOptions.vue
launcher/src/components/UI/the-staking/StakingScreen.vue
launcher/src/components/UI/the-staking/StateDropdown.vue
launcher/src/components/UI/the-staking/TotalBalance.vue
launcher/src/components/UI/the-staking/ValidatorStats.vue

FIX: validator stats ui

---

launcher/src/components/UI/node-page/components/node/ClientButtons.vue
launcher/src/composables/services.js

After adding tooltips, the buttons had issues and didn't work initially, but the problem has been resolved and they are functioning correctly now

Resolve Issue with Client Buttons

---

launcher/src/components/UI/node-header/NotifModal.vue

the beaconcha modal is already deactivated

update the notification modal

---

launcher/src/backend/Monitoring.js
launcher/src/components/UI/node-page/sections/PluginLogs.vue
launcher/src/components/UI/task-manager/SubTasks.vue

fixes #930
and some other smaller stuff mentionied here: #861

ADD: Stereum QOL Changes

---

launcher/src/backend/ValidatorAccountManager.js
launcher/src/background.js
launcher/src/composables/validators.js
launcher/src/store/ControlService.js

deleting keys from list of keys `/etc/stereum/keys.yaml` after clicking `remove key`

FIX: validator keys grouping

---

launcher/public/output.css
launcher/src/components/UI/one-click/sections/AnimationSection.vue

Remove the bubbles
Add installing services

ADD: new action to oneclick anim

---

launcher/public/output.css
launcher/src/components/UI/one-click/sections/AnimationSection.vue
launcher/src/components/UI/the-staking/EnterPassword.vue
launcher/src/components/UI/the-staking/ExitMultipleValidators.vue
launcher/src/components/UI/the-staking/FeeRecipient.vue
launcher/src/components/UI/the-staking/GrafitiMultipleValidators.vue
launcher/src/components/UI/the-staking/InsertValidator.vue
launcher/src/components/UI/the-staking/SearchBox.vue
launcher/src/components/UI/the-staking/SearchOptions.vue
launcher/src/components/UI/the-staking/SelectService.vue

CHANGE: staking page panels position
REMOVE: grouping icon on staking page

REFACTOR: oneclick anim

---

launcher/public/output.css
launcher/src/backend/ServiceManager.js
launcher/src/components/UI/edit-page/EditScreen.vue
launcher/src/components/UI/edit-page/components/changes/ChangesBox.vue
launcher/src/components/UI/edit-page/components/modals/SwitchContent.vue

REPLACED: randonId by service id

FIX: removing network

---

launcher/public/output.css
launcher/src/components/UI/edit-page/EditScreen.vue
launcher/src/components/UI/edit-page/components/changes/ChangeAnimation.vue
launcher/src/components/UI/edit-page/components/edit/ConsensusClients.vue
launcher/src/components/UI/edit-page/components/edit/ExecutionClients.vue
launcher/src/components/UI/edit-page/components/edit/ValidatorClients.vue
launcher/src/components/UI/edit-page/components/modals/SwitchContent.vue
launcher/src/components/UI/edit-page/components/service/ServiceBody.vue

ADD: validation flag to new client

---

launcher/src/languages/en.json

Includes some fixes for currently used strings.

Update language strings fixing some errors

---

launcher/src/components/UI/services-modal/EnrGenerator.vue
launcher/src/components/UI/services-modal/ObolModal.vue

update obolModal and ENR generator to composition api

REFACTOR: obolModal and ENR generator 

---

controls/roles/update-changes/molecule/202/converge.yml
controls/roles/update-changes/molecule/202/molecule.yml
controls/roles/update-changes/molecule/202/playbook.yml
controls/roles/update-changes/molecule/202/prepare.yml
controls/roles/update-changes/molecule/202/verify.yml
controls/roles/update-changes/tasks/2.0.2/erigon_dbTag.yaml
controls/roles/update-changes/tasks/2.0.2/updates-202.yaml
controls/roles/update-changes/tasks/main.yml
launcher/src/backend/OneClickInstall.js
launcher/src/backend/ethereum-services/ErigonService.js
launcher/src/components/UI/edit-page/components/drawer/DrawerFilter.vue
launcher/src/components/UI/node-manage/SidebarManage.vue

Added Erigon Tags `prune=htc`,`prune.r.before`,`--rpc.returndata.limit=1000000`, `--db.pagesize=16K'` and `--db.size.limit=8TB`
Also added Update Script for tag `db.size.limit=8TB`
Erigon now available for gnosis
Erigon Archive Config fixed

UPDATE: Erigon Config

---

launcher/src/components/UI/node-page/NodeScreen.vue
launcher/src/components/UI/node-page/components/alert/NodeAlert.vue
launcher/src/components/UI/the-control/ControlAlert.vue
launcher/src/store/nodeHeader.js

the expert mode in the node page with click on the no fee recipient alarm

Fix the bugs for release

---

launcher/public/output.css
launcher/src/components/UI/staking-page/StakingScreen.vue
launcher/src/components/UI/staking-page/components/list/ListPanels.vue
launcher/src/components/UI/staking-page/components/list/rows/GroupRow.vue

FIX: missing components

---

launcher/src/store/nodeManage.js

Added Archive Node option to all Networks in the One Click Install

ADD: Archive Node Options

---

launcher/src/components/UI/node-header/IconsNav.vue
launcher/src/components/UI/node-header/ReconnectModal.vue
launcher/src/composables/services.js
launcher/src/languages/ar.json
launcher/src/languages/bg.json
launcher/src/languages/cs.json
launcher/src/languages/de.json
launcher/src/languages/en.json
launcher/src/languages/es.json
launcher/src/languages/fa.json
launcher/src/languages/fr.json
launcher/src/languages/it.json
launcher/src/languages/ja.json
launcher/src/languages/mn.json
launcher/src/languages/nl.json
launcher/src/languages/pt.json
launcher/src/languages/ru.json
launcher/src/languages/sr.json
launcher/src/languages/tr.json
launcher/src/languages/vi.json
launcher/src/languages/zh.json

Added reconnect modal for manual reconnection

ADD: Reconnect Modal

---

launcher/src/components/UI/node-header/ServiceLinks.vue
launcher/src/store/nodeManage.js

Remove Relayoor Relay for Mainnet / Check MEV Relays Active the obol modal frontend for the wiring

UPDATE the main net relays

---

launcher/src/components/UI/the-control/AmsterdamComponent.vue
launcher/src/components/UI/the-control/EpochSlot.vue
launcher/src/components/UI/the-control/NoData.vue
launcher/src/components/UI/the-control/PeerToPeer.vue
launcher/src/components/UI/the-control/SyncStatus.vue
launcher/src/components/UI/the-control/TheBalance.vue
launcher/src/store/theFooter.js

Amsterdam widget updated
SyncStatus widget updated
No data layer updated
balance widget
p2p widget

Update:improve no date layer

---

launcher/public/output.css
launcher/src/components/UI/multi-server/components/login-form/LoginForm.vue
launcher/src/components/UI/multi-server/components/saved-servers/SavedServers.vue
launcher/src/components/UI/staking-page/StakingScreen.vue
launcher/src/components/UI/staking-page/components/list/ListBody.vue
launcher/src/components/UI/staking-page/components/list/ListHeader.vue
launcher/src/components/UI/staking-page/components/list/rows/KeyRow.vue
launcher/src/components/base/BaseLayout.vue
launcher/src/components/base/InstallationLayout.vue

CHANGe: some changes for multi servers

FIX: staking page error

---

launcher/public/output.css
launcher/src/components/UI/edit-page/EditScreen.vue
launcher/src/components/UI/edit-page/components/changes/ChangeAnimation.vue
launcher/src/components/UI/edit-page/components/modals/CustomModal.vue
launcher/src/components/UI/one-click/components/presets/PresetHeader.vue
launcher/src/components/UI/staking-page/components/list/panels/PasswordPanel.vue
launcher/src/components/UI/staking-page/components/modals/RemoveValidators.vue
launcher/src/composables/services.js
launcher/src/store/nodeManage.js
launcher/vue.config.js

FIX: typo
FIX: change confirm animation size

FIX: stop importing doppelganger process 

---

launcher/public/output.css
launcher/src/components/UI/edit-page/components/edit/NetworkDetails.vue
launcher/src/components/UI/server-management/MultiServerScreen.vue
launcher/src/components/UI/server-management/components/login-form/LoginForm.vue
launcher/src/components/UI/server-management/components/saved-servers/ServerRow.vue
launcher/src/components/UI/server-management/components/server-update/ListRow.vue
launcher/src/components/UI/server-management/components/server-update/UpdateRow.vue
launcher/src/components/UI/server-management/components/server-update/UpdateServer.vue

Empty field validation errors
Update OS some fixes

FIX: server management some fixes

---

launcher/src/backend/Monitoring.js

FIX: beacon API for dencun fork

---

launcher/src/backend/NodeConnection.js

FIX: latest stereum version in updatepanel (dev mode)

---

launcher/src/backend/ServiceManager.js
launcher/src/components/UI/node-page/components/alert/NodeAlert.vue

FIX: not loading icons and cleared relays

---

launcher/src/components/UI/base-header/components/modals/UpdatePanel.vue

- Improve loading speed
- Fix style of OS updates badge
- Fix variable: numberOfUpdatablePackages
- Fix method: getUpdatablePackagesCount()
- Remove method: getUpgradablePackages()

FIX: os updates in updatepanel

---

launcher/public/output.css
launcher/src/components/UI/edit-page/components/modals/custom-service/AddCustom.vue
launcher/src/components/UI/server-management/MultiServerScreen.vue
launcher/src/components/UI/server-management/components/login-form/LoginForm.vue
launcher/src/components/UI/server-management/components/saved-servers/ServerRow.vue
launcher/src/components/UI/staking-page/StakingScreen.vue
launcher/src/components/UI/staking-page/components/list/ListBody.vue
launcher/src/components/UI/staking-page/sections/ListSection.vue
launcher/src/components/layers/TheFooter.vue
launcher/src/composables/useLogin.js

fixed #1769 
fixed staking page disabling on mounting
fixed #1763

FIX: release bugs

---

launcher/src/components/UI/server-management/components/saved-servers/ServerPanel.vue
launcher/src/components/UI/services-modal/SsvModal.vue
launcher/src/languages/en.json

- fixed operator explorer url for mainnet
- added registered operator metadata to dashboard
- adjusted content of backup readme if ssv api is unavailable
- fixes #1778

FIX: ssv modal and server filter

---

launcher/src/components/UI/base-header/components/menu/MenuBody.vue
launcher/src/components/UI/base-header/components/menu/SingleMenu.vue
launcher/src/components/UI/node-page/sections/ExpertWindow.vue

Fix issue #1774 
Fix issue #1773

Fix the header update icon and Fee Recipient Option in settings

---

.vscode/extensions.json
.vscode/settings.json
.vscode/snippets.code-snippets
controls/roles/manage-service/tasks/nimbus-checkpoint-sync.yml
launcher/src/backend/OneClickInstall.js
launcher/src/backend/ethereum-services/BesuService.js
launcher/src/backend/ethereum-services/LodestarValidatorService.js
launcher/src/backend/ethereum-services/RethService.js
launcher/src/components/UI/edit-page/components/modals/SwitchContent.vue
launcher/src/components/UI/edit-page/components/modals/SwitchModal.vue

resolves #1680 - CC Archive Tags
also fixes a bug where after replacing a service the checkpoint tag wasn't added

FIX: archive tags not applied for CCs

---

launcher/CONTRIBUTING.md
launcher/src/backend/Monitoring.js

chore: fix typos

---

launcher/public/output.css
launcher/src/components/UI/base-header/components/modals/UpdatePanel.vue
launcher/src/components/UI/server-management/MultiServerScreen.vue
launcher/src/store/servers.js

FIX the navigation from update panel to server managment update panel

---

launcher/src/components/UI/node-page/sections/ExpertWindow.vue

Fixes https://github.com/stereum-dev/ethereum-node/issues/1838

FIX: remove unexpected double quote

---

launcher/src/backend/Monitoring.js
launcher/src/backend/NodeConnection.js
launcher/src/backend/SSHService.js
launcher/src/components/UI/server-management/MultiServerScreen.vue

Logouts were processed asynchronously and new connections were tried to create without a finished logout, resulting in weird issues.

FIX: Login Issues

---

.github/workflows/test-molecule.yml
controls/roles/update-changes/molecule/214/converge.yml
controls/roles/update-changes/molecule/214/molecule.yml
controls/roles/update-changes/molecule/214/playbook.yml
controls/roles/update-changes/molecule/214/prepare.yml
controls/roles/update-changes/molecule/214/verify.yml
controls/roles/update-changes/tasks/2.1.4/sdvt_changes.yaml
controls/roles/update-changes/tasks/2.1.4/updates-214.yaml
controls/roles/update-changes/tasks/main.yml
launcher/src/backend/Monitoring.js
launcher/src/backend/NodeConnection.js
launcher/src/backend/ServiceManager.js
launcher/src/backend/ValidatorAccountManager.js
launcher/src/backend/ethereum-services/BesuService.js
launcher/src/backend/ethereum-services/LighthouseValidatorService.js
launcher/src/backend/ethereum-services/LodestarValidatorService.js
launcher/src/backend/ethereum-services/NimbusValidatorService.js
launcher/src/backend/ethereum-services/TekuValidatorService.js
launcher/src/backend/tests/integration/BesuService.int.js
launcher/src/backend/tests/integration/ErigonService.int.js
launcher/src/backend/tests/integration/FlashbotsMevBoostService.int.js
launcher/src/backend/tests/integration/GethService.int.js
launcher/src/backend/tests/integration/LighthouseBeaconService.int.js
launcher/src/backend/tests/integration/LodestarBeaconService.int.js
launcher/src/backend/tests/integration/NethermindService.int.js
launcher/src/backend/tests/integration/NimbusBeaconService.int.js
launcher/src/backend/tests/integration/PrysmBeaconService.int.js
launcher/src/backend/tests/integration/TekuBeaconService.int.js
launcher/src/components/UI/node-page/sections/ExpertWindow.vue

- Replaced Goerli with holesky for Integration tests
- Removed a deprecate tag from Besu standard config
- Fixed double Quotes issue properly 😅 (fixes #1838)
- Fixed Custom installation for Services which have charon as dependency (it failed when charon was installed in one step with the specific services)

FIX: Some smaller Issues

---

launcher/public/output.css
launcher/src/backend/AuthenticationService.js
launcher/src/components/UI/server-management/components/two-factor-auth/TwoFactoSetupBox.vue
launcher/src/components/UI/server-management/components/two-factor-auth/TwoFactorAuth.vue

Fixed minor bugs and retested the two-actor authentication feature to ensure functionality.

FIX the 2FA functionality

---

launcher/public/output.css
launcher/src/components/UI/node-page/components/alert/NodeAlert.vue
launcher/src/components/UI/the-control/ControlAlert.vue
launcher/src/components/UI/the-control/SyncStatus.vue
launcher/src/store/theControl.js

FIX: sync status error alarm

---

launcher/public/output.css
launcher/src/components/UI/server-management/MultiServerScreen.vue
launcher/src/components/UI/server-management/components/modals/QRcodeModal.vue
launcher/src/components/UI/server-management/components/two-factor-auth/TwoFactoSetupBox.vue
launcher/src/components/UI/server-management/components/two-factor-auth/TwoFactorAuth.vue
launcher/src/languages/en.json
launcher/src/store/twoFactorAuth.js

FIX: 2FA Setup - UI Improvements

---

launcher/src/components/UI/staking-page/components/modals/ImportValidator.vue
launcher/src/components/layers/TheFooter.vue

close: https://github.com/stereum-dev/ethereum-node/issues/1762

Response window with Slashing DB 

---

launcher/public/output.css
launcher/src/components/UI/server-management/MultiServerScreen.vue

FIX: SSH Key List refresh after adding new key

---

launcher/src/components/UI/edit-page/EditScreen.vue

- Properly differs between service and setup to delete
- Fixes #1936

FIX: delete service or setup via edit node

---

launcher/public/output.css
launcher/src/components/UI/edit-page/EditScreen.vue
launcher/src/components/UI/edit-page/components/edit/setups/RenameSetup.vue
launcher/src/components/UI/edit-page/components/edit/setups/SetupMenu.vue
launcher/src/components/UI/edit-page/components/edit/setups/SingleSetup.vue
launcher/src/components/UI/edit-page/components/modals/setups/CreateSetup.vue
launcher/src/components/UI/node-page/NodeScreen.vue
launcher/src/components/UI/node-page/components/node/NodeBody.vue
launcher/src/components/UI/node-page/components/node/clients/ConsensusClients.vue
launcher/src/components/UI/node-page/components/node/clients/ExecutionClients.vue
launcher/src/components/UI/the-control/DataApi.vue
launcher/src/components/UI/the-control/RpcEndpoint.vue
launcher/src/components/UI/the-control/WsEndpoint.vue
launcher/src/components/layers/NetworkStatus.vue
launcher/src/composables/multiSetups.js
launcher/src/composables/pingQuality.js
launcher/src/composables/services.js
launcher/src/store/theNode.js

- Fix high CPU usage
- Fix Clients disapearing after installing

FIX: CPU Issue

---

launcher/src/components/UI/edit-page/components/drawer/DrawerFilter.vue

Fixes the missing ssv.network service  in "_Edit Node -> Add Service_" dialog on Holesky.

FIX: missing ssv.network service on holesky edit node

---

launcher/src/backend/ethereum-services/SSVNetworkService.js

Set default value for SSV logs to 28

REFACTOR: set ssv logs default value to 28

---

launcher/src/components/UI/the-control/AmsterdamComponent.vue

Fix immediate display of slots and epochs after setup change

---

launcher/public/output.css
launcher/src/components/UI/edit-page/components/edit/SyncCarousel.vue
launcher/src/components/UI/node-page/components/modals/ResyncModal.vue

[Bug Fix]: Disable Checkpoint Sync Option for Execution Clients in Resync UI

---

launcher/public/output.css
launcher/src/components/UI/language-page/components/MenuBody.vue
launcher/src/components/UI/node-page/components/alert/NodeAlert.vue
launcher/src/components/UI/the-control/ControlAlert.vue

 Filter out of the buttons at the top with three categories

---

launcher/public/output.css
launcher/src/components/UI/node-page/sections/SidebarSection.vue

[Bug Fix]: Correct Slightly Misplaced Command Buttons on Node Page

---

launcher/src/components/UI/custom-installation/components/CustomPath.vue
launcher/src/components/UI/one-click/components/plugin/ConfigFooter.vue
launcher/src/components/UI/one-click/components/plugin/InstallationPath.vue
launcher/src/store/clickInstallation.js

ADD: validation on the installation path

---

README.md

Hey. A link to the project site has been added

Docs: A link to the project site has been added

---

launcher/package.json
launcher/public/output.css
launcher/src/background.js
launcher/src/components/UI/node-page/components/alert/NodeAlert.vue
launcher/src/components/UI/setting-page/components/VolumeSlider.vue
launcher/src/components/UI/the-control/ControlAlert.vue
launcher/src/preload.js
launcher/src/store/theFooter.js

Extend Audio Settings to use OS Audio Management Systems

---

launcher/package.json
launcher/public/output.css
launcher/src/background.js
launcher/src/components/UI/node-page/components/alert/NodeAlert.vue
launcher/src/components/UI/setting-page/components/VolumeSlider.vue
launcher/src/components/UI/the-control/ControlAlert.vue
launcher/src/preload.js
launcher/src/store/theFooter.js

Reverts stereum-dev/ethereum-node#2107

Revert "Extend Audio Settings to use OS Audio Management Systems"

---

launcher/src/components/UI/welcome-page/components/WelcomeFooter.vue

Tell the user to use ubuntu.

---

.github/workflows/electron.yaml

Make sure runners run on a specific node version

FIX: Build

---

launcher/src/components/UI/staking-page/StakingScreen.vue
launcher/src/components/UI/staking-page/components/management/components/val-rewards/TotalBalance.vue
launcher/src/components/UI/staking-page/components/modals/WithdrawMultiple.vue

Release fix

---

launcher/public/output.css
launcher/src/backend/SSHService.js
launcher/src/components/UI/control-page/components/fragments/EndpointServiceLine.vue

FIX: rpc request

---

launcher/src/backend/ServiceManager.js

restarts prometheus/grafana on edit node page changes if installed

ADD: Prometheus/Grafana auto restart

---

launcher/package.json

added email und url to author
bump version

FIX: building pipeline [DRAFT]

---

launcher/src/backend/ethereum-services/PrysmBeaconService.js
launcher/src/backend/ethereum-services/PrysmValidatorService.js
launcher/src/components/UI/edit-page/components/drawer/SetupsDrawer.vue

devnet prysm beacon & validator cmd

FIX: devnet

---

launcher/public/output.css
launcher/src/components/UI/edit-page/EditScreen.vue
launcher/src/components/UI/node-page/NodeScreen.vue

fixes: https://github.com/stereum-dev/ethereum-node/issues/2106

FIX: remove setup services right after creating setup

---

README.md

Updates X (Twitter) badge to reflect rebranding.

docs: Update X (Twitter) Badge

---

controls/roles/manage-service/molecule/notifications/verify.yml
controls/roles/update-changes/molecule/224/prepare.yml
controls/roles/update-changes/molecule/224/verify.yml
controls/roles/update-changes/tasks/2.2.4/reth_changes.yaml
launcher/src/backend/ethereum-services/RethService.js

i just changed the existing script that added the tag in such a way that it removes it.

REMOVE: legacy tag from reth

---

controls/roles/update-changes/molecule/232/converge.yml
controls/roles/update-changes/molecule/232/molecule.yml
controls/roles/update-changes/molecule/232/playbook.yml
controls/roles/update-changes/molecule/232/prepare.yml
controls/roles/update-changes/molecule/232/verify.yml
controls/roles/update-changes/tasks/2.3.2/ssv_changes.yaml
controls/roles/update-changes/tasks/2.3.2/updates-232.yaml
controls/roles/update-changes/tasks/main.yml
launcher/src/backend/OneClickInstall.js
launcher/src/backend/ServiceManager.js
launcher/src/backend/ethereum-services/SSVDKGService.js
launcher/src/components/UI/edit-page/components/modals/AddConnection.vue
launcher/src/components/UI/edit-page/components/modals/AddModal.vue
launcher/src/components/UI/edit-page/components/modals/ModifyContent.vue
launcher/src/components/UI/edit-page/components/service/ServiceBody.vue

- Add support for SSV DKG 3.0.0+ (fixes #2176)
- Improve handling of DKG service on Edit Node page

REFACTOR: implement ssv dkg v3 support

---

launcher/src/backend/Monitoring.js
launcher/src/languages/tr.json
launcher/src/languages/zh.json

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

launcher/public/output.css
launcher/src/components/UI/control-page/ControlScreen.vue
launcher/src/components/UI/control-page/components/cards/MiniCard.vue
launcher/src/components/UI/control-page/components/cards/ThinCard.vue
launcher/src/components/UI/control-page/components/cards/WidgetCard.vue
launcher/src/components/UI/control-page/components/widgets/ConnectedClientPair.vue
launcher/src/components/UI/control-page/components/widgets/VolumeWidget.vue
launcher/src/components/UI/import-config/components/ImportingSyncing.vue
launcher/src/components/UI/node-page/components/node/clients/ClientButtons.vue
launcher/src/components/UI/one-click/components/sync/components/TheCarousel.vue
launcher/src/components/UI/server-management/components/saved-servers/ServerPanel.vue

- Added current version on server management
- Refactored server buttons on server management
- Fixed importing servers

FIX: release fixes

---

.github/ISSUE_TEMPLATE/bug_report.yml

Use input fields for environment & OS

UPDATE: modify bug report template 

---

controls/roles/2fa-enable/tasks/main.yaml

fixes: https://github.com/stereum-dev/ethereum-node/issues/1976

FIX: 2FA issue with ubuntu-24.04

---

launcher/vue.config.js

fix vue config based on @0xwitty recommendations

FIX: Remove css-loader from vue config

---

launcher/public/output.css
launcher/src/components/UI/terminal-page/components/TerminalPanel.vue
launcher/src/composables/useTerminal.js

FIX: launcher shell issues

---

launcher/src/background.js

reverting unnecessary changes for launcher update

FIX: revert launcher update
