stereum-dev/ethereum-node

- controls/roles/fastsync/tasks/main.yml
Attempt to fix the following issue with molecule tests:
```
TASK [fastsync : Download latest blockchain snapshots] *************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.timeout: The read operation timed out
fatal: [manage-service--ssv-nimbus--ubuntu-20.04]: FAILED! => {"changed": false, "elapsed": 0, "msg": "failed to create temporary content file: The read operation timed out"}
changed: [manage-service--ssv-nimbus--centos-stream-8]
```
https://github.com/stereum-dev/ethereum-node/runs/5036655609?check_suite_focus=true#step:7:279
> FIX:molecule fastsync timeout

- controls/roles/setup/tasks/main.yml
- controls/roles/setup/tasks/zip-centos.yml
Issue:
```
TASK [fastsync : Deflate blockchain snapshot archives] *************************
fatal: [fastsync--default--centos-stream-8]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/lighthouse-latest.tar.gz\". Make sure the required command to extract the file is installed. Unable to find required 'unzip' or 'zipinfo' binary in the path. Command \"/usr/bin/gtar\" could not handle archive."}
```
https://github.com/stereum-dev/ethereum-node/runs/5048410396?check_suite_focus=true#step:7:271
> FIX:centos lacks zip pkgs in some versions

- controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
- controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
- controls/roles/manage-service/molecule/ssv-teku/verify.yml
Issue:
```
TASK [debug] *******************************************************************
ok: [manage-service--ssv-teku--centos-stream-8] => {
"msg": {
"changed": true,
"cmd": "docker ps",
"delta": "0:00:00.058989",
"end": "2022-02-02 17:41:09.936993",
"failed": false,
"msg": "",
"rc": 0,
"start": "2022-02-02 17:41:09.878004",
"stderr": "",
"stderr_lines": [],
"stdout": "CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                        PORTS                                                                                    NAMES\n053c6ad076b2   bloxstaking/ssv-node:latest-ubuntu   \"bash -c 'touch /dat…\"   10 seconds ago   Restarting (2) 1 second ago …
```
> FIX:molecule ssv check ports after services boot

- controls/roles/setup/tasks/main.yml
forgot to filter for centos when installing packages via `yum`
> FIX:yum only when centos

- controls/roles/manage-service/molecule/ssv-lighthouse/converge.yml
- controls/roles/manage-service/molecule/ssv-lighthouse/create.yml
- controls/roles/manage-service/molecule/ssv-lighthouse/molecule.yml
- controls/roles/manage-service/molecule/ssv-lighthouse/prepare.yml
- controls/roles/manage-service/molecule/ssv-lighthouse/verify.yml
- controls/roles/manage-service/molecule/ssv-nimbus/converge.yml
- controls/roles/manage-service/molecule/ssv-nimbus/create.yml
- controls/roles/manage-service/molecule/ssv-nimbus/molecule.yml
- controls/roles/manage-service/molecule/ssv-nimbus/prepare.yml
- controls/roles/manage-service/molecule/ssv-nimbus/verify.yml
- controls/roles/manage-service/molecule/ssv-teku/converge.yml
- controls/roles/manage-service/molecule/ssv-teku/create.yml
- controls/roles/manage-service/molecule/ssv-teku/molecule.yml
- controls/roles/manage-service/molecule/ssv-teku/prepare.yml
- controls/roles/manage-service/molecule/ssv-teku/verify.yml
This PR addresses multiple issues:
- No need for infura.io eth1 addresses on github action hetzner vms, there are 2 Geth instances running on a private network `10.10.0.0/24` the test VMs can join. `10.10.0.2` for websocket and `10.10.0.3` for RESTful endpoints.
- Checking output of logs of running services in `stderr` instead of `stdout`. `docker logs` always writes to `stderr`, e. g. `docker ps` writes like everything else to `stdout´.
> FIX:molecule static geth & docker log verify

- launcher/src/components/UI/CircleLoading.vue
`<div class="progress" v-if="active">` caused the progress bar not being rendered but the message gets rendered in this div.
> FIX: mistake from Conflict

- .github/workflows/test-molecule.yml
We hit the rate limit of simultaneous server creation requests with Hetzner. This PR prevents a large number of concurrent server creation requests by introducing a delay configurable by scenario.
> FIX: prevent hitting test vm rate limit of Hetzner

- launcher/src/backend/ethereum-services/GrafanaService.js
avoiding `/grafana/grafana` dirs
> FIX: grafana volume directories

- launcher/src/backend/ethereum-services/GethService.js
Geth config in `/etc/stereum/services` now looks like this:
```
command: geth --goerli --http --http.port=8545 --http.addr=0.0.0.0
--http.vhosts="*" --allow-insecure-unlock
--http.api="db,eth,net,web3,personal" --ws --ws.port=8546 --ws.addr=0.0.0.0
--ws.api="db,eth,net,web3" --ws.origins="*"
```
> FIX: geth config, fixes #202

- controls/roles/fastsync/molecule/default/create.yml
- controls/roles/manage-service/molecule/monitor-lighthouse/create.yml
- controls/roles/manage-service/molecule/monitor-nimbus/create.yml
- controls/roles/manage-service/molecule/ssv-lighthouse/create.yml
- controls/roles/manage-service/molecule/ssv-nimbus/create.yml
- controls/roles/manage-service/molecule/ssv-prysm/create.yml
- controls/roles/manage-service/molecule/ssv-teku/create.yml
- controls/roles/manage-service/molecule/start-multiple/create.yml
- controls/roles/manage-service/molecule/start-stop/create.yml
- controls/roles/manage-service/molecule/start/create.yml
- controls/roles/manage-service/molecule/write-start/create.yml
- controls/roles/setup/molecule/default/create.yml
- controls/roles/update-services/molecule/default/create.yml
- controls/roles/validator-import-api/molecule/lighthouse/create.yml
- controls/roles/validator-import-api/molecule/nimbus/create.yml
- controls/roles/validator-import-api/molecule/prysm/create.yml
- controls/roles/validator-import-lighthouse/molecule/default/create.yml
- controls/roles/validator-import-nimbus/molecule/default/create.yml
- controls/roles/validator-import-prysm/molecule/default/create.yml
- controls/roles/validator-import-teku/molecule/default/create.yml
I found that the VMs having trouble to connect to the virtual network were only in the US, according to the documentation [here](https://docs.hetzner.cloud/#network-zones) the virtual networks in US don't connect to the ones in Europe.
This hopefully fixes the issue we have with attaching the molecule test vms to the virtual network for execution client connections.
> FIX: force test vms to hel1 to connect to geth

- launcher/src/backend/ethereum-services/BloxSSVService.js
- launcher/src/backend/ethereum-services/BloxSSVService.test.js
- launcher/src/backend/ethereum-services/GethService.js
- launcher/src/backend/ethereum-services/GethService.test.js
- launcher/src/backend/ethereum-services/GrafanaService.js
- launcher/src/backend/ethereum-services/GrafanaService.test.js
- launcher/src/backend/ethereum-services/LighthouseBeaconService.js
- launcher/src/backend/ethereum-services/LighthouseBeaconService.test.js
- launcher/src/backend/ethereum-services/LighthouseValidatorService.js
- launcher/src/backend/ethereum-services/LighthouseValidatorService.test.js
- launcher/src/backend/ethereum-services/NimbusBeaconService.js
- launcher/src/backend/ethereum-services/NimbusBeaconService.test.js
- launcher/src/backend/ethereum-services/NodeService.js
- launcher/src/backend/ethereum-services/PrometheusNodeExporterService.js
- launcher/src/backend/ethereum-services/PrometheusNodeExporterService.test.js
- launcher/src/backend/ethereum-services/PrometheusService.js
- launcher/src/backend/ethereum-services/PrometheusService.test.js
This is necessary to update config files when breaking changes happen for Stereum versions as well as service versions.
fixes #137
> ADD: config version for service yamls

- controls/roles/manage-service/molecule/ssv-prysm/prepare.yml
error: `could not connect to the eth1 client` https://github.com/stereum-dev/ethereum-node/runs/6425742182?check_suite_focus=true#step:8:1121
> FIX: ssv-prysm eth1 link

- .github/workflows/test-molecule.yml
- controls/roles/validator-import-api/molecule/lighthouse/prepare.yml
- controls/roles/validator-import-api/molecule/nimbus/prepare.yml
- controls/roles/validator-import-lighthouse/molecule/default/prepare.yml
- controls/roles/validator-import-lighthouse/molecule/default/verify.yml
- controls/roles/validator-import-lighthouse/tasks/main.yml
- controls/roles/validator-import-nimbus/molecule/default/prepare.yml
- controls/roles/validator-import-nimbus/molecule/default/verify.yml
- controls/roles/validator-import-nimbus/tasks/main.yml
https://github.com/stereum-dev/ethereum-node/issues/214
https://github.com/stereum-dev/ethereum-node/issues/213
https://github.com/stereum-dev/ethereum-node/issues/210
> FIX: replace stereum/* docker images in molecule tests & EDIT: CLI import is deactivated

- controls/finishUpdate.yaml
- controls/unattended-update.sh
This PR introduces a way to implement patches running custom ansible roles & tasks on update via `controls/finishUpdate.yaml`. Similar process is used in Stereum version 1.x
> ADD: patches for updates

- controls/defaults/stereum_defaults.yaml
- controls/roles/fastsync/molecule/default/prepare.yml
- controls/roles/manage-service/molecule/geth/converge.yml
- controls/roles/manage-service/molecule/geth/prepare.yml
- controls/roles/manage-service/molecule/monitor-lighthouse/converge.yml
- controls/roles/manage-service/molecule/monitor-lighthouse/prepare.yml
- controls/roles/manage-service/molecule/monitor-nimbus/converge.yml
- controls/roles/manage-service/molecule/monitor-nimbus/prepare.yml
- controls/roles/manage-service/molecule/monitor-prysm/converge.yml
- controls/roles/manage-service/molecule/monitor-prysm/prepare.yml
- controls/roles/manage-service/molecule/monitor-teku/converge.yml
- controls/roles/manage-service/molecule/monitor-teku/prepare.yml
- controls/roles/manage-service/molecule/ssv-lighthouse/converge.yml
- controls/roles/manage-service/molecule/ssv-lighthouse/prepare.yml
- controls/roles/manage-service/molecule/ssv-nimbus/converge.yml
- controls/roles/manage-service/molecule/ssv-nimbus/prepare.yml
- controls/roles/manage-service/molecule/ssv-prysm/converge.yml
- controls/roles/manage-service/molecule/ssv-prysm/prepare.yml
- controls/roles/manage-service/molecule/ssv-teku/converge.yml
- controls/roles/manage-service/molecule/ssv-teku/prepare.yml
- controls/roles/manage-service/molecule/start-multiple/prepare.yml
- controls/roles/manage-service/molecule/start-stop/prepare.yml
- controls/roles/manage-service/molecule/start/prepare.yml
- controls/roles/manage-service/molecule/write-start/converge.yml
- controls/roles/ssv-key-generator/molecule/default/converge.yml
docker image versions are now managed centralized via `stereum.defaults.versions`
> FIX: molecule tests now use versions of defaults

- controls/roles/manage-service/molecule/monitor-bloxssv/converge.yml
- controls/roles/manage-service/molecule/monitor-bloxssv/prepare.yml
- controls/roles/manage-service/molecule/monitor-bloxssv/verify.yml
- controls/roles/manage-service/molecule/monitor-geth/converge.yml
- controls/roles/manage-service/molecule/monitor-geth/prepare.yml
- controls/roles/manage-service/molecule/monitor-geth/verify.yml
- controls/roles/manage-service/molecule/monitor-lighthouse/converge.yml
- controls/roles/manage-service/molecule/monitor-lighthouse/prepare.yml
- controls/roles/manage-service/molecule/monitor-lighthouse/verify.yml
- controls/roles/manage-service/molecule/monitor-nimbus/converge.yml
- controls/roles/manage-service/molecule/monitor-nimbus/prepare.yml
- controls/roles/manage-service/molecule/monitor-nimbus/verify.yml
- controls/roles/manage-service/molecule/monitor-prysm/converge.yml
- controls/roles/manage-service/molecule/monitor-prysm/prepare.yml
- controls/roles/manage-service/molecule/monitor-prysm/verify.yml
- controls/roles/manage-service/molecule/monitor-teku/converge.yml
- controls/roles/manage-service/molecule/monitor-teku/prepare.yml
- controls/roles/manage-service/molecule/monitor-teku/verify.yml
- controls/roles/manage-service/tasks/main.yml
- controls/roles/manage-service/tasks/write-prometheus-configuration.yml
- controls/roles/manage-service/templates/prometheus.yml
- launcher/src/backend/ethereum-services/PrometheusService.js
- launcher/src/backend/ethereum-services/PrometheusService.test.js
resolves #433 
Please note:
- Prometheus needs to be kicked off to reload the config (done via task `Reload config (prometheus only)`)
- Prometheus looks into resolving automatic reload: https://github.com/prometheus/prometheus/issues/9783
- Prometheus needs a flag to allow reloading via HTTP: `--web.enable-lifecycle`
- All services configs need a `service` tag, otherwise prometheus won't start because the generation of the template fails
> ADD: prometheus automized config generation

- launcher/src/background.js
When the stereum launcher is executing some critical tasks the user must confirm to exit (if the user ignores it well what can i do 😅)
fixes #456
> ADD: closing dialog

- controls/roles/setup/tasks/main.yml
fixing issue introduced with #492 
The default values (like installation path) are now set only when not already filled. `stereum` variable get's set by `controls/genericPlaybook.yaml` which is used by Stereum Launcher.
> FIX: set default values when necessary on setup

- controls/roles/setup/tasks/docker-ubuntu.yaml
- controls/roles/ssv-key-generator/molecule/default/prepare.yml
Instead using a `loop:` which processes each package installation individually this PR makes `apt` installing all packages at once.
> When used with a loop: each package will be processed individually, it is much more efficient to pass the list directly to the name option.
Source: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#notes
> FIX: installing all packages at once

- .github/workflows/test-molecule.yml
- controls/roles/validator-import-api/molecule/prysm/verify.yml
- controls/roles/validator-list-api/molecule/prysm/verify.yml
- removing test for setting fee recipient for github actions only: doesn't work because of testnet implementation not ready yet.
- checking prysm not in logs but with api call, this way log can be full of unsynced-messages/-warnings and we still know if it's working or not
> Fix molecule prysm verify

- controls/roles/configure-updates/tasks/main.yml
- controls/roles/update-os/.yamllint
- controls/roles/update-os/molecule/default/converge.yml
- controls/roles/update-os/molecule/default/create.yml
- controls/roles/update-os/molecule/default/destroy.yml
- controls/roles/update-os/molecule/default/molecule.yml
- controls/roles/update-os/molecule/default/playbook.yml
- controls/roles/update-os/molecule/default/prepare.yml
- controls/roles/update-os/molecule/default/verify.yml
- controls/roles/update-os/molecule/run-stereum-service-update/converge.yml
- controls/roles/update-os/molecule/run-stereum-service-update/create.yml
- controls/roles/update-os/molecule/run-stereum-service-update/destroy.yml
- controls/roles/update-os/molecule/run-stereum-service-update/molecule.yml
- controls/roles/update-os/molecule/run-stereum-service-update/playbook.yml
- controls/roles/update-os/molecule/run-stereum-service-update/prepare.yml
- controls/roles/update-os/molecule/run-stereum-service-update/verify.yml
- controls/roles/update-os/tasks/main.yml
- controls/roles/update-stereum/tasks/main.yml
- controls/stereum-services-update.sh
- controls/unattended-update.sh
covers some parts of #552 
- update os
- reboot if necessary
- resume with stereum- & service-updates (after reboot or immediately)
technical documentation: https://github.com/stereum-dev/ethereum-node/wiki/Unattended-Updates#role-update-os
> ADD: update-os & wiring with unattended update

- launcher/src/backend/NodeConnection.js
- launcher/src/backend/OneClickInstall.js
- launcher/src/backend/ValidatorAccountManager.js
- launcher/src/backend/ethereum-services/BloxSSVService.js
- launcher/src/backend/ethereum-services/BloxSSVService.test.js
- launcher/src/background.js
> FIX: Blox SSV config formatting

- launcher/src/backend/ValidatorAccountManager.js
- launcher/src/components/UI/node-manage/NodeConfiguration.vue
- launcher/src/components/UI/the-staking/FinishModal.vue
- launcher/src/components/UI/the-staking/KeyTable.vue
- launcher/src/store/theStaking.js
fixes #594 
fixes #593 
there is not a pop up that shows the status of the import:
when there is no error it says: "<number of keys> Keys were imported!"
if there is it prints the error
@maxbehzadi82 you may need to make some ui changes i just copied the delete modal from `FormSetup.vue` and changed it up a little bit 😅
> ADD: key import error handling

- launcher/src/backend/ethereum-services/SSVNetworkService.js
It's the wrong contract address, and ssv network now has the correct one as default. So we don't need it in the config.
> FIX: remove ssv network contract of config file

- launcher/src/backend/NodeConnection.int.js
- launcher/src/backend/ethereum-services/BesuService.int.js
- launcher/src/backend/ethereum-services/GethService.int.js
- launcher/src/backend/ethereum-services/LighthouseBeaconService.int.js
- launcher/src/backend/ethereum-services/NethermindService.int.js
- launcher/src/backend/ethereum-services/NimbusBeaconService.int.js
- launcher/src/backend/ethereum-services/PrysmBeaconService.int.js
- launcher/src/backend/ethereum-services/TekuBeaconService.int.js
- tests weren't pulling service versions from api (jest-env: node)
- some tests vms weren't strong enough
- vm locations are no longer fixed
- removed subnetworks from tests (no longer used)
- updated expects (verifys)
tested these changes locally and and on my forked repo via workflow
> UPDATE: Integration Tests

- launcher/src/backend/NodeConnection.js
By setting the env var `IS_DEV=true`
Stereum-Controls-Updates are always updating to HEAD of main
> ADD: updating to HEAD

- launcher/src/components/UI/the-staking/DisplayValidators.vue
Bug 1: Keys that are in the process of being deleted weren't marked red ✅ 
Bug 2: Beaconcha.in returns data of `null` instead of `[]` for invalid (not deposited) keys which led to an error ✅
> FIX: Bugs on staking page

- launcher/src/components/UI/the-control/DataApi.vue
- launcher/src/components/UI/the-control/RpcEndpoint.vue
Until port mapping for existing nodes is implemented via ansible
> REFACTOR: disable rpc and datapi widgets

- launcher/src/backend/ethereum-services/PrysmBeaconService.js
- launcher/src/backend/ethereum-services/PrysmBeaconService.test.js
`http-web3provider` is deprecated
[DOCs](https://docs.prylabs.network/docs/prysm-usage/parameters)
> UPDATE: Prysm config

- controls/defaults/stereum_defaults.yaml
CL
lighthouse: https://github.com/sigp/lighthouse/releases/tag/v3.1.2
nimbus: https://github.com/status-im/nimbus-eth2/releases/tag/v22.10.1
teku: https://github.com/ConsenSys/teku/releases/tag/22.10.1
lodestar: https://github.com/ChainSafe/lodestar/releases/tag/v1.1.0
EL
besu: https://github.com/hyperledger/besu/releases/tag/22.7.6
nethermind: https://github.com/NethermindEth/nethermind/releases/tag/1.14.3
erigon: https://github.com/ledgerwatch/erigon/releases/tag/v2.28.1
Others:
mevboost: https://github.com/flashbots/mev-boost/releases/tag/v1.3.2
blox-SSV: https://github.com/bloxapp/ssv/releases/tag/v0.3.3
Monitoring:
grafana: https://github.com/grafana/grafana/releases/tag/v9.2.1
node_exporter: https://github.com/prometheus/node_exporter/releases/tag/v1.4.0
prometheus: …
> UPDATE: update docker images in molecule test

- controls/roles/manage-service/tasks/main.yml
Sometimes, especially on mainnet, Geth loses its state and needs to resync from an old data point. This causes unnecessary downtime.
This fix also helps other services to gracefully shutdown with a higher timeout on stopping services.
> FIX: geth losing state on start/stop

- launcher/src/backend/NodeConnection.js
- launcher/src/backend/ServiceManager.js
- launcher/src/backend/ethereum-services/NodeService.js
- launcher/src/background.js
- launcher/src/components/UI/node-header/IconsNav.vue
- launcher/src/store/ControlService.js
- Installation paths where normalized based on operating system and not linux
- when connecting mevboost to new not installed yet service, task failed
- reset stored stereum settings on logout
> FIX: bugs before release 

- launcher/src/backend/ValidatorAccountManager.js
- launcher/src/background.js
- launcher/src/components/UI/the-staking/DisplayValidators.vue
- launcher/src/store/ControlService.js
aliases of validator keys are stored and loaded from `/etc/stereum/keys.yaml`
Structure:
```
<pubkey>: alias
<pubkey>: alias
<pubkey>: alias
....
```
> ADD: Pubkey Alias Storage

- controls/defaults/stereum_defaults.yaml
lh: https://github.com/sigp/lighthouse/releases/tag/v3.2.1
nimbus: https://github.com/status-im/nimbus-eth2/releases/tag/v22.10.1
teku: https://github.com/ConsenSys/teku/releases/tag/22.11.0
prysm: https://github.com/prysmaticlabs/prysm/releases/tag/v3.1.2
lodestar: https://github.com/ChainSafe/lodestar/releases/tag/v1.2.1
geth: https://github.com/ethereum/go-ethereum/releases/tag/v1.10.26
nethermind: https://github.com/NethermindEth/nethermind/releases
mevboost: https://github.com/flashbots/mev-boost/releases
ssv: https://github.com/bloxapp/ssv/releases
grafana: https://github.com/grafana/grafana/releases
prometheus: https://github.com/grafana/grafana/releases
> UPDATE: docker images in molecule test

- launcher/src/backend/Monitoring.js
Tested on Ubuntu 22. 
Storage was been reported in TB by "df", this fix makes it always return value in GBs
> Fix storage dashboard

- launcher/src/backend/ethereum-services/TekuBeaconService.js
This is a safety feature on teku and is disabled by stereum
> Use validator lockfiles on teku

- .github/workflows/test-molecule.yml
- controls/roles/manage-service/molecule/mevboost-besu-teku/converge.yml
- controls/roles/manage-service/molecule/mevboost-geth-teku/converge.yml
- controls/roles/manage-service/molecule/mevboost-nethermind-teku/converge.yml
- controls/roles/update-changes/molecule/20-rc9/converge.yml
- controls/roles/update-changes/molecule/20-rc9/molecule.yml
- controls/roles/update-changes/molecule/20-rc9/playbook.yml
- controls/roles/update-changes/molecule/20-rc9/prepare.yml
- controls/roles/update-changes/molecule/20-rc9/verify.yml
- controls/roles/update-changes/tasks/2.0-rc6/fix-prysm-822.yaml
- controls/roles/update-changes/tasks/2.0-rc6/updates-20-rc6.yaml
- controls/roles/update-changes/tasks/2.0-rc7/updates-20-rc7.yaml
- controls/roles/update-changes/tasks/2.0-rc9/teku_changes.yaml
- controls/roles/update-changes/tasks/2.0-rc9/updates-20-rc9.yaml
- controls/roles/update-changes/tasks/main.yml
- controls/roles/update-services/tasks/update-service.yml
- controls/roles/validator-delete-api/molecule/teku/prepare.yml
- controls/roles/validator-fee-recipient-api/molecule/teku/prepare.yml
- controls/roles/validator-import-api/molecule/teku/prepare.yml
- controls/roles/validator-list-api/molecule/teku/prepare.yml
- launcher/src/backend/OneClickInstall.js
- launcher/src/backend/ServiceManager.js
- launcher/src/backend/ValidatorAccountManager.js
- launcher/src/backend/ethereum-services/TekuBeaconService.int.js
- launcher/src/components/UI/the-staking/DisplayValidators.vue
This PR includes a rollout in form of a `update-changes` role and fixes this problem for all future fresh installs of teku
This PR also fixes update-services. it used to fail when a service config included a network which was not defined in updates.json. (e.g. `goerli.LighthouseBeaconService` would not be defined)
When a validator import fails and the api response doesn't include an error code nor an error message, the whole msg is displayed to avoid something like : `Validator Import Failed: undefined undefined`
update-changes was looking for files that include the service name (e.g. `LighthouseBeaconService`) this caused files that included this string in their dependencies also to be included. fixed this by specificly checking for `service_config.service`
> ADD: teku cert rollout

- launcher/src/components/UI/the-control/PeerToPeer.vue
- launcher/src/components/UI/the-control/SyncStatus.vue
- Made sure that the NoDataLayer is only shown after the widget has at least one time successfully initialized
- Cleaned dead code from SyncStatus Widget
> REFACTOR: prevent nodatalayer on first load in p2p- and syncstatus widget

- launcher/package-lock.json
- launcher/src/backend/NodeConnection.js
- launcher/src/background.js
- launcher/src/components/UI/custom-installation/CustomInstallationLayer.vue
- launcher/src/components/UI/node-header/MainNavbar.vue
- launcher/src/components/UI/plugin-installation/VerifyInstallation.vue
- launcher/src/pages/TheNode.vue
- launcher/src/store/ControlService.js
This checks for a requireed restart and restarts accordingly.
Optimised refresh loops to prevent errors while connection cuts when the node restarts.
closes #413
> ADD: Restart after initial Setup

- controls/roles/manage-service/molecule/erigon-lodestar/converge.yml
- controls/roles/manage-service/molecule/erigon-lodestar/verify.yml
- launcher/src/backend/ethereum-services/ErigonService.js
Erigon changed their default behaviour:
By default the Engine API is disabled in favour of Erigon native Embedded Consensus Layer, if you want to either stake or sync an external Consensus Layer, run Erigon with flag `--externalcl`.
> FIX: Erigon Config

- launcher/src/backend/ethereum-services/LighthouseBeaconService.js
- launcher/src/backend/ethereum-services/TekuBeaconService.js
I made a mistake and added the gnosis bootnodes to the main config of Lighthouse and Teku.
Bootnodes are now only added when the configured network is `gnosis`
> FIX: Bootnodes only for gnosis

- launcher/src/store/nodeManage.js
Added the mainnet ultra sound relay ([relay.ultrasound.money](https://relay.ultrasound.money)). The relay has 13.6% of validators connected and is one of the top relays by number of blocks included on-chain (see [relayscan.io](https://relayscan.io)).
Note: the `icon: "/img/icon/click-installation/testnet-circle.png"` also needs changing :)
> add mainnet ultra sound relay

- .github/workflows/test-molecule.yml
- controls/defaults/stereum_defaults.yaml
- controls/roles/manage-service/molecule/mevboost-erigon-lodestar/converge.yml
- controls/roles/manage-service/molecule/nethermind-teku-gnosis/converge.yml
- controls/roles/update-changes/molecule/20-rc12/verify.yml
- controls/roles/update-changes/tasks/main.yml
- controls/roles/validator-delete-api/molecule/lodestar/prepare.yml
- controls/roles/validator-fee-recipient-api/molecule/lodestar/prepare.yml
- controls/roles/validator-import-api/molecule/lodestar/prepare.yml
- controls/roles/validator-list-api/molecule/lodestar/prepare.yml
- launcher/src/backend/OneClickInstall.js
- launcher/src/backend/ethereum-services/NethermindService.js
- launcher/src/components/UI/node-manage/AddPanel.vue
- launcher/src/components/UI/plugin-installation/PluginName.vue
new gnosis nodes will use `gnosis` instead of `xdai`
mistake in the service config
if the path of the largest volume was the root dir the install directory ended up with `/stereum`
changed to `/opt/stereum` when path of largest volume equals `/`.
chooses path of largest volume when installing via custom installation
the right image version is now queried
readded update-changes script and tests for next release
> UPDATE: Nethermind, qol changes

- launcher/src/backend/SSHService.js
- launcher/src/background.js
reloading the app in dev mode, caused the app to throw an error due to `tunnel-ssh` configured with `autoClose: true` some tunnels where closed some not and at the same time the app was already looking for new free ports to open which then caused this issue
> FIX: tunnel issue

- launcher/src/components/UI/plugin-installation/NetworkSelect.vue
some pinia stored values that are used throughout the OneClickInstallation were not set
> FIX: OneClickInstallation network issue

- launcher/src/backend/ServiceManager.js
When changing the mev config `--payload-builder=true` was always added to nimbus
> FIX: Nimbus MevBoost Dependencies

- launcher/src/components/UI/the-staking/DisplayValidators.vue
fixing validator state: `active since` on Gnosis 
gnosis Epoch time: 80 sec while goerli and mainnet 384sec
> FIX: gnosis active since calculation

- launcher/src/backend/Monitoring.js
The backend tried requesting on a closed connection which resulted in an error.
> FIX: nuking the node

- controls/roles/manage-service/tasks/main.yml
- launcher/src/pages/TheNode.vue
Add `overwrite: false` to your grafana config via `Expert Mode` to keep your custom dashboards, contact points etc...
Changed the sorting for the Services on the right for the `Node Manage` Page, so if you change your view the icons stay the same position.
> ADD: overwrite ignore for grafana

- launcher/src/backend/Monitoring.js
Besu is the only EC that currently does report sync stats properly to Prometheus.
This workaround requests the sync status for all other EC by BEACON/RPC API and fixes #1274.
> FIX: show sync status also for EC not reporting stats properly

- launcher/src/backend/ServiceManager.js
Clients who's config have been changed through client switching now restart afterwards
> FIX: Client restart on switch

- launcher/src/components/UI/the-node/TheExpert.vue
1.  Change the current button name to "**Apply & Restart**"
2. Add another button to the client / service settings, that can be used to run the old function of just simply applying the config, next the current implementation of "Apply & Restart"
> additional button to have both "Apply" and "Apply & Restart"

- launcher/src/components/UI/the-control/AmsterdamComponent.vue
When operating on an Ethereum network following the ETH consensus, the component aligns with an epoch of 32 slots, each updating every 12 seconds. In contrast, when interacting with the Gnosis network, the component adjusts to an epoch length of 16 slots and a faster slot update interval of 6 seconds.
> Update Amsterdam comp. with the Gnosis Network

- launcher/src/components/UI/the-control/AmsterdamComponent.vue
- launcher/src/components/UI/the-control/ControlGrid.vue
- launcher/src/components/UI/the-control/SyncStatus.vue
- launcher/src/components/UI/the-control/TooltipDialog.vue
- launcher/src/store/theFooter.js
Redo the Amsterdam component to add pre justify row and also create a dialog on top of the widget to be more user-friendly
> redo the Amsterdam comp.

- launcher/src/components/UI/the-control/SyncStatus.vue
- launcher/src/components/UI/the-control/TooltipDialog.vue
Because of the developed tooltip some of the align in sync status widgets were messy, and also the position of the new tooltip fixed related to the chosen component
> fix the tooltip positions

- launcher/src/backend/NodeConnection.js
- launcher/src/backend/ServiceManager.js
- launcher/src/components/UI/the-node/TheExpert.vue
- launcher/src/store/services.js
The Teku Valdiator Export Mode now includes a button which removes validator lockfiles. this should make it easier for users to resolve their teku issues after teku crashes. fixes #1050
Changes to service configs via Expert Mode are now checked for the correct format before writing.
Tht `write yaml` task will fail if the format is not correct. fixes #1272
> ADD: format check, lockfile delete button

- launcher/src/backend/NodeConnection.js
- launcher/src/backend/OneClickInstall.js
- launcher/src/store/nodeManage.js
- Bloxroute ethical relay removed
- Restart failed sometimes on setup
- Monitoring loop tried to get service configs and failed due to missing `/etc/stereum/services` directory. On OneClickInstallations Stereum now creates not only `/etc/stereum` but `/etc/stereum/services` as well
> REMOVE: Bloxroute ethical relay

- launcher/src/backend/ServiceManager.js
- launcher/src/components/UI/the-node/JournalNode.vue
Fixed a bug were services which haven't been started once would throw an error on restart or resync
> FIX: restart/resync of services

- controls/roles/manage-service/molecule/mevboost-nethermind-lighthouse/converge.yml
- controls/roles/manage-service/molecule/mevboost-nethermind-nimbus/converge.yml
- controls/roles/manage-service/molecule/mevboost-nethermind-prysm/converge.yml
- controls/roles/manage-service/molecule/mevboost-nethermind-teku/converge.yml
- controls/roles/manage-service/molecule/monitor-nethermind/prepare.yml
- controls/roles/manage-service/molecule/nethermind-lighthouse/converge.yml
- controls/roles/manage-service/molecule/nethermind-nimbus/converge.yml
- controls/roles/manage-service/molecule/nethermind-prysm/converge.yml
- controls/roles/manage-service/molecule/nethermind-teku-gnosis/converge.yml
- controls/roles/manage-service/molecule/nethermind-teku/converge.yml
- controls/roles/update-changes/molecule/20-rc10/prepare.yml
- controls/roles/update-changes/molecule/20-rc12/prepare.yml
- controls/roles/update-changes/molecule/20-rc13/prepare.yml
- controls/roles/update-changes/molecule/20-rc18/prepare.yml
- launcher/src/backend/ethereum-services/NethermindService.js
- launcher/src/backend/ethereum-services/NethermindService.test.js
We renamed the Nethermind executable from `Nethermind.Runner` to `nethermind`. This PR updates all references to those.
To be merged once the next version of Nethermind is released.
> Update Nethermind executable name

- launcher/src/backend/NodeConnection.js
- The passwordless sudo check with "sudo -l" fails
- Check with "sudo hostname" works as expected
fixes #1473
credits @very-common 🚀
> FIX: passwordless sudo detection

- launcher/src/components/UI/edit-page/EditScreen.vue
- launcher/src/components/UI/edit-page/components/edit/NetworkDetails.vue
- launcher/src/components/UI/edit-page/components/modals/NetworkModal.vue
This should prevent the network state to be undefined at any time.
> FIX: Network State issues

- launcher/src/backend/NodeConnection.js
- launcher/src/backend/ethereum-services/SSVNetworkService.js
- launcher/src/background.js
- launcher/src/components/UI/services-modal/SsvDashboard.vue
- launcher/src/components/UI/services-modal/SsvModal.vue
- launcher/src/store/ControlService.js
- launcher/src/store/nodeManage.js
- Add support for SSV on holesky
- Fix "My Operator Page" URL for specific network (#1486)
- Fix GUI for existing operator (#1486)
> REFACTOR: add support for ssv on holesky and bugfixes

- launcher/src/backend/Monitoring.js
Remove Prometheus NodeExporter service from storage query (extends #1095)
> REFACTOR: remove nodexporter from storage query

- launcher/src/backend/Monitoring.js
- launcher/src/backend/ValidatorAccountManager.js
fix: https://github.com/stereum-dev/ethereum-node/issues/1451
finalized Epoch from beacon-API is just manually reduced once
> FIX: distinguish finalized & preJustified epochs on Control tab

- .github/workflows/electron.yaml
As It seams do you need to update `actions/download-artifact` together with `actions/upload-artifact`
And as `actions/upload-artifact` is fixed with `v2` and `actions/download-artifact` is always at `master` the versions mismach. https://github.com/actions/download-artifact/issues/267
> UPDATE: electron.yaml

- launcher/src/components/UI/the-control/TheBalance.vue
This PR adds a color-coded balance widget display: green for positive balances and red for negatives.
> Update Balance widget: Green for Positive, Red for Negative

- launcher/src/components/UI/node-header/NotifModal.vue
Non-core items such as SSV or OBOL from Beaconcha.in the modal were removed.
> UPDATE: filter the validator to show from beaconcha modal

- launcher/src/components/UI/the-control/TheBalance.vue
Negative balance on macOS, before:
Fix:
> FIX: color of negative balance on macOS

- launcher/src/components/UI/base-header/components/modals/UpdatePanel.vue
Updating all services with a click on "Update all" does currently not work due to wrong definition of variables.
This PR fixes this bug.
> FIX: update all services method

- launcher/src/components/UI/node-page/components/logs/LogHeader.vue
the image version shown in the header of the logs, was once the actual running image version. this probably got lost in the transition to the new design, so i fixed this in this pr.
> FIX: running image version got lost with new design

- launcher/src/components/UI/base-header/sections/LogoSection.vue
- launcher/src/components/UI/server-management/MultiServerScreen.vue
- launcher/src/components/UI/server-management/components/login-form/LoginForm.vue
- launcher/src/components/UI/server-management/components/saved-servers/ServerPanel.vue
> Enhance the Server Management Modal

- launcher/public/output.css
- launcher/src/backend/ValidatorAccountManager.js
- launcher/src/components/UI/services-modal/EnrGenerator.vue
> Improve Responisveness Obol Generate ENR Modal

- launcher/src/backend/ValidatorAccountManager.js
If importing more than 100 keys with password files, only the first 100 would be imported. A wrong password batch was assigned for the other batches
> FIX: Validator Import with Password Files

- launcher/src/store/services.js
Change title of option in validator client settings from "Doppelganger" to "Doppelganger Protection"
> Fix Naming of Doppelganger to Doppelganger Protection in settings

- launcher/src/store/services.js
Naming of Doppelganger to Doppelganger Protection in settings for rest of the Clients
> FIX: Naming of Doppelganger to Doppelganger Protection in settings for rest of the Clients

- launcher/src/backend/ConfigManager.js
- Function yaml.safeDump is removed in js-yaml
- Use yaml.dump instead, which is now safe by default.
> FIX: use yaml dump to write multi setup

- launcher/src/backend/NodeConnection.js
Reset existing SSV database if operator key changes on:
- importing an encrypted SSV key
- importing an unencrypted SSV key
- importing an (old) unencrypted SSV key and migrate this key to a (new) encrypted SSV key
- creating a new encrypted SSV key
> FIX: ssv keychange

- launcher/src/backend/NodeUpdates.js
**Description**:
This pull request fixes an issue in the log message where the text `"get count pd updating os packages"` was incorrectly used. The intended message is `"get count of updating OS packages"`. This error occurred in two methods: `getCurrentOsVersion` and `getCountOfUpdatableOSUpdate`.
**Changes made**:
- Updated the log message in both methods to reflect the correct phrasing: `"Error occurred during get count of updating OS packages:\n"`
**Importance**:
Correcting this log message improves the clarity of error reporting. The original message was unclear due to the use of "pd" instead of the correct phrase, which could cause confusion when debugging. This fix ensures that the log provides accurate and understandable information about errors during the process of counting OS …
> Fix error in log message Update NodeUpdates.js

- launcher/.eslintrc.js
- launcher/src/backend/web3/CSM.js
- launcher/src/background.js
- launcher/src/store/ControlService.js
Below is an example output from the `getSigningKeysWithQueueInfo` function when called with `nodeOperatorId = 39`. 
This example demonstrates how the function returns an array of signing keys, each associated with a `queuePosition`. A `queuePosition` of `0` indicates that the key is not in the deposit queue, while non-zero values specify the position within the deposit queue.
```json
[
{
"key": "0x93a7...3d63ef",
"queuePosition": 0
},
{
"key": "0x891b...970631",
"queuePosition": 0
},
{
"key": "0x830e...bdad68",
"queuePosition": 0
},
{
"key": "0xac05...63ae6f",
"queuePosition": 0
},
{
"key": "0x9420...9e25e",
"queuePosition": 0
},
{
"key": "0xa846...a8f62f",
"queuePosition": 0
},
{
"key": "0xb002...fef903e",
"queuePosition": 0
},
{
"key": "0xa889...06ab8e",
"queuePosition": 0
},
{
"key": …
```
> ADD: getSigningKeysWithQueueInfo

- launcher/CONTRIBUTING.md
A typo in the documentation where the command `run npm run format` was incorrectly written.
The extra `run` before `npm` has been removed, so the correct command is now `npm run format`.
> docs: Fix incorrect command in documentation Update CONTRIBUTING.md

- controls/README.md
I noticed a typo in the command `molcule test -s <scenario-name>`.
The correct spelling should be `molecule`. I've fixed this in the documentation.  
Additionally, I corrected a small spelling mistake in the sentence: "You'll need to have docker and python with pip intalled." 
The word "intalled" should be "installed."
> docs: Fix typo in command and correct spelling

- launcher/src/backend/ValidatorAccountManager.js
> FIX: Escaping Problem of Passwords on Import

- launcher/src/components/UI/edit-page/EditScreen.vue
- launcher/src/components/UI/edit-page/components/modals/AddModal.vue
- launcher/src/components/UI/edit-page/components/modals/ModifyContent.vue
- launcher/src/components/UI/edit-page/components/service/ServiceBody.vue
- Fix bug where static "randomId" var breaks installer
- Use dynamic classes for "Config Services" items
- Avoid JS errors if no mev boost item is choosen
- Avoid JS errors if service has no dependencies
- Show "Add Connection" dialog for new KAPI service
> FIX: item handling on edit node page

- launcher/vue.config.js
I corrected an issue where the `vue-loader` and `css-loader` were being applied incorrectly in the Webpack config.
Instead of passing them as two parameters, I’ve updated it to use an array, which is the proper way to define multiple loaders in Webpack. This should fix the issue and ensure that the loaders are applied properly.
> fix: incorrect usage of `vue-loader` and `css-loader` in Webpack config

- launcher/vue.config.js
Reverts stereum-dev/ethereum-node#2242
> Revert "fix: incorrect usage of `vue-loader` and `css-loader` in Webpack config"

- controls/roles/2fa-remove/tasks/main.yaml
Fixes an issue when removing 2FA on Ubtuntu 24.04
Same as #2246 but for the "2fa-remove" task.
> FIX: 2FA remove issue on ubuntu-24.04

- launcher/src/components/UI/staking-page/StakingScreen.vue
When users export a signed voluntary-exit message, the file currently contains the entire response object (wrapped in a `data` property).  
This PR cleans up the export so that **only the raw exit message JSON is saved**, with no surrounding `data` wrapper—both for single- and multi-validator exports.
Key change  
• `saveExitMessage()` now strips any optional `data` field before writing the file.
fixes #2255
>  Remove `data` wrapper from exported voluntary-exit messages

- controls/roles/update-services/tasks/main.yml
- controls/roles/update-stereum/tasks/main.yml
- launcher/src/backend/NodeConnection.js
- launcher/src/backend/NodeUpdates.js
- launcher/src/backend/tests/unit/NodeConnection.test.js
makes use of the `lane` setting in the `stereum settings`.
values:
- `dev` will fetch `updates.dev.json`
- `prod (or anything else bc default)` will fetch `updates.json`
> ADD: dev lane for updates.json

- .github/workflows/code_quality_check.yml
- .github/workflows/electron.yaml
- .github/workflows/lint.yml
- .github/workflows/shellcheck.yml
- .github/workflows/test-integration-legacy.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-jest.yml
- .github/workflows/test-molecule.yml
Bumps checkout to v5 for future-proofing against Node 24 runner updates.
Requires runner v2.327.1+. Workflows compile the same.
Ref: https://github.com/actions/checkout/releases/tag/v5.0.0
> chore(ci): upgrade checkout to v5
